[DNM] Improved antagonist managing tools for admins part 1.
unitystation/unitystation pull request #10046
Opened 2023-09-01 21:51 UTC by SerheyKr

### Purpose
PR partially implements #5816  - adding custom objective, ability to manage peoples objectives and review them

### Notes:
Gonna implement rest of stuff later (such as team tasks and their management, ghost roles management and etc.)

### Changelog:
[New] New tools for admins to manage objectives

2023-10-07 00:20 UTC, corp-0 commented
we will do a test build after tomorrow's playtest for this PR

2023-10-09 04:39 UTC, corp-0 requested changes
I read like half of the PR, it is long.

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Items/Traits/CommonTraits.cs
> -	[Obsolete]
why did you remove the obsolete attribute?

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Items/Traits/CommonTraits.cs
> +		return everyTraitOutThere.ElementAt(index);
if possible, we need to find a different solution for this because using that field should be a sin.

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Player/Mind.cs
> +				antagContainer = GetComponent<SpawnedAntag>();
if you need to ensure this is available, I would rather cache the component on ``Awake`` than this.

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObjects/GhostRoleList.cs
> +		public short GetIndex(GhostRoleData ghostRole)
I think it would be better to have a unique ID instead of handling them by index

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Systems/Antagonists/AntagData.cs
> +		public Antagonist FromIndexAntag(short index)
same here. I find index to be unreliable. Add a unique ID to every antag we spawn with the ``Guid.NewGuid()``. Same for objectives.

You can then store them in a dictionary and use the ID as key to get them later.

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Systems/Antagonists/Objective.cs
> +		[HideInInspector]
change these to ``[NonSerialized]`` instead or better yet, make them properties.

``public string PlayerID {get; set;}``

2023-10-09 04:39 UTC, corp-0 commented on UnityProject/Assets/Scripts/Systems/Antagonists/Objective.cs
> +		[SerializeField]
public fields don't need the ``SerializedField`` attribute.

2023-10-19 06:52 UTC, MaxIsJoe commented
Some notes from testing on 19/10/2023:


![image](https://github.com/unitystation/unitystation/assets/34368774/1268d928-6e65-420c-a4c9-82ddd62a1d07)

- Team Objectives should have a "Round not ready" screen to avoid problems before the round starts.

![image](https://github.com/unitystation/unitystation/assets/34368774/1adeccf2-f46b-41e4-9468-71ef9a3d2e41)

- You can set ghost roles without their requirements ever getting met. (example: Adding a cyborg brain role without any brains present for ghosts to possess)

![image](https://github.com/unitystation/unitystation/assets/34368774/4f768497-fadd-4308-8466-7c829c4c8cd6)

- Team objectives reports no players on the station team?

![image](https://github.com/unitystation/unitystation/assets/34368774/8e9e393c-46f0-480f-958f-00c3dd2beb5a)

- A choised?

![image](https://github.com/unitystation/unitystation/assets/34368774/4177d85e-14e1-4b6d-8669-c5e6a50b4149)

- Input field needs a background to be clear that you can write there

![image](https://github.com/unitystation/unitystation/assets/34368774/d9a3370b-9304-4602-8b5d-afa1cd631ae9)

- Custom objective progress have a new line for some reason? Also the progress on them appears before the round even ends.

2023-10-19 07:55 UTC, AtnerNT commented
Don’t think the custom objectives showing completion before round end is an issue, I honestly think that should be true for any objective that can completed prior to round end (like assassinate objectives). Stuff like escape and steal objectives are obviously only completed in round end, but other than that I don’t think that is an issue.

2023-10-21 00:07 UTC, corp-0 commented
we will merge this and playtest it tomorrow. Any further issue we find has to be tackled in following PRs

2023-10-21 00:08 UTC, corp-0 commented
ah fuck you have a conflict

2023-10-22 18:18 UTC, merged