Improve space movement
unitystation/unitystation pull request #10260
Opened 2024-01-13 15:19 UTC by Bod9001

still not perfect but a lot better than it was
Details,
The one issue was the Synchronise check to make sure your floating in the right direction and all that stuff, doesn't account for
latency if you have network prediction, so added that check into account for the latency,

Next made it so When you get in range of a tile you round to the position of the tile, this helps with the annoying issue with server and client slightly disagreeing on where the players, and since then the request is sent on write the edge of the tile it would cause issues so, now it's a bit more resilient

### Changelog:

CL: [Improvement] Improve space movement

2024-01-13 16:44 UTC, corp-0 requested changes

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +		int matrixID, float inSpinFactor, bool forceOverride, uint doNotUpdateThisClient, float TimeSent)
```suggestion
		int matrixID, float inSpinFactor, bool forceOverride, uint doNotUpdateThisClient, float timeSent)
```

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +		if (IsFlyingSliding && 0 > (TimeSpentFlying - TimeSent))
```suggestion
		if (IsFlyingSliding && (TimeSpentFlying - TimeSent) < 0)
```
I think this conveys better the intention and read better at first sight.

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +				Loggy.LogError(TimeDifference.ToString());
remove this debug logging

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +				Loggy.LogError("diff Sent in Compared actual " + (resetToLocal - transform.localPosition).ToString() );
more debug logging

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +		var dd = NetworkTime.time;
looks like you are not using this variable anywhere

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +			var floating = IsFloating();
why use a variable here instead of ``if (IsFloating() == false)`` directly?

2024-01-13 16:44 UTC, corp-0 commented on UnityProject/Assets/Scripts/Player/MovementV2/MovementSynchronisation.cs
> + 			if (PositionDifference < 0.50f)
magical number

2024-01-13 16:46 UTC, Bod9001 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +				Loggy.LogError(TimeDifference.ToString());
oh yeah, forgot to remove it

2024-01-14 17:21 UTC, Bod9001 commented
requested changes done

2024-01-14 21:43 UTC, merged