More minigames & Abandoned Crate Improvements PT 1 (Reflection Golf)
unitystation/unitystation pull request #10350
Opened 2024-05-01 10:10 UTC by AtnerNT

This PR is the first of a few but this ended up having alot of changes so I am splitting it into several PRs so its easier to review.

This first PR adds a new minigame, reflection golf that will be the first of a few new minigames added to abandoned crates as well as new sprites for abandoned crates.

This PR isnt quite ready yet but most the remaining stuff requires no code so Ill be opening as draft.

Remaining things to do:
-> Make some sprite work for the buttons and improve the light sprites in the Reflection Golf GUI
-> Design more reflection golf puzzles
-> Info button for minigame UI to explain the rules of the games. (Possibly link to wiki page? Lemme know which is preferable)

Following PRs will add more minigames to abandoned crates

### Changelog:

CL: [New] Added 'Reflection Golf' Minigame to abandoned crates.
CL: [Improvement] Added new spritework for abandoned crates
CL: [Fix] Fixed abandoned crates not unlocking on game completion
CL: [Fix] Fixed abandoned crates not being able to be hand interacted with to be opened/closed
CL: [Balance] Mapped a small amount of abandoned crates onto Relicta and Maintrooms, replacing some loot that was previously just in regular chests or on floor.

2024-05-06 08:41 UTC, Bod9001 commented
Looks good

2024-09-25 16:22 UTC, AtnerNT commented
Ready for review/merge

2024-09-25 16:27 UTC, MaxIsJoe requested changes

2024-09-25 16:27 UTC, MaxIsJoe commented on CodeScanList.json
> +                    "string Combine(string, string, string, string)"
Codescan changes must be done in a separate PR

2024-09-25 16:27 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/MiniGames/MiniGameModules/ReflectionGolf/ReflectionGolfInput.cs
> +public class ReflectionGolfInput
namespace

2024-09-25 16:27 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/MiniGames/MiniGameModules/ReflectionGolf/ReflectionGolfLevel.cs
> +				Loggy.LogError($"MiniGames/RelfectionGolfLevel.cs at line 61. The specified file path does not exist! {path}");
follow our standard for writing logs
https://unitystation.github.io/unitystation/contribution-guides/Development-Standards-Guide/#0-in-code-documentation-and-clarity

2024-09-26 10:38 UTC, AtnerNT commented
If there's no further reviews, this is ready to merge now.

2024-09-26 10:55 UTC, MaxIsJoe approved these changes

2024-09-26 10:55 UTC, merged