Implement telescopic shield/ eshield, make Dual esword wielded
unitystation/unitystation pull request #10537
Opened 2024-09-26 11:41 UTC by AutumnNova

this pr deleted wieldable and rips out half of the energysword code, replacing them with an event based system that allows for sharing common behaviour between activatable weapons and easily adding in extra behaviour

As a result Dual eswords have been made wieldable, the energysword script has been modified to only do roundstart color randomisation plus the screwdriver/multitool interactions and the energydagger doesnt throw like 5 errors if you try to use it

Also implements the telescopic shield, energy combat shield and bananium shield, which are tiny sized items that can be activated, making them a large item which works as a shield, 50% block chance for all 3 of them

I plan to convert over stun batons/telescopic batons to this system in a followup because their existing code is kind of awful

### Changelog:
CL: [Balance] Dual esword requires wielding
CL: [New] Implements the Telescopic shield, Combat energy shield and Bananium shield

2024-09-26 21:39 UTC, MaxIsJoe requested changes

2024-09-26 21:39 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/Items/Weapons/ActivatableWeaponComponents/Client/PreventHandswapWhileActive.cs
> +namespace Items
Namespaces are meant to reflect the folder/file structure, don't have two of them at once.

2024-09-26 21:39 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/Items/Weapons/ActivatableWeaponComponents/Client/ChangeSpriteOnActivate.cs
> +		private void Awake()
function in the middle of field declarations

2024-09-27 09:17 UTC, Bod9001 approved these changes

2024-09-27 09:17 UTC, merged