Sttaging bug fixes
unitystation/unitystation pull request #10613
Opened 2024-11-18 00:50 UTC by Bod9001

### Changelog:

CL: [New] Adds a Italian Speech modifier to fake moustache and fixes speech modifier bug
CL: [Improvement] improves the logic for graffiti and Mopping graffiti off walls

CL: [Fix] Fixes door not opening on bump interaction
CL: [Fix] Fixes graffiti rendering above the player

2024-11-21 16:47 UTC, corp-0 commented on UnityProject/Assets/Scripts/HealthV2/Living/Damage/Trauma/TraumaTypes/TraumaBurning.cs
> +							$"<color=red>Parts of the {bodyPart.gameObject.ExpensiveName()} crumble and ash away.</color>");
REEEEEEEEEEEEEEEEEE use the rich text thingy I created for exactly this

2024-11-21 17:55 UTC, MaxIsJoe approved these changes

2024-11-21 17:55 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/Items/Tool/Mop.cs
> -		if (MatrixManager.IsWallAt(interaction.WorldPositionTarget.RoundToInt(), isServer: side == NetworkSide.Server))
why is this removed?

2024-11-21 17:55 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/ScriptableObjects/SpeechModifier.cs
> +				if ((i == message.Length - 1))
why the double (())

2024-11-21 17:55 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/ScriptableObjects/SpeechModifier.cs
> +				if (!char.IsSeparator(c) && !char.IsPunctuation(c) && (i != message.Length -1) ) continue;
! is for inverting in this case only reee

2024-11-23 00:53 UTC, corp-0 commented on UnityProject/Assets/Scripts/HealthV2/Living/Damage/Trauma/TraumaTypes/TraumaBurning.cs
> +							$"<color=red>Parts of the {bodyPart.gameObject.ExpensiveName()} crumble and ash away.</color>");
```suggestion
bodyPart.gameObject.ExpensiveName().Color(Color.Red);
```

2024-11-23 19:01 UTC, MaxIsJoe commented
when did i approve this
no

2024-11-23 19:02 UTC, MaxIsJoe requested changes
reviewws

2024-11-23 22:03 UTC, Bod9001 commented on UnityProject/Assets/Scripts/Items/Tool/Mop.cs
> -		if (MatrixManager.IsWallAt(interaction.WorldPositionTarget.RoundToInt(), isServer: side == NetworkSide.Server))
So you can clean graffiti on walls

2024-11-23 22:06 UTC, MaxIsJoe approved these changes

2024-11-23 22:40 UTC, merged