Fix1066
unitystation/unitystation pull request #1069
Opened 2018-05-15 19:43 UTC by NinjaDanz3r

### Purpose
This PR adds pixel perfect zooming and resolution. Fixes #1066 and fixes #836.
Might also resolve #880 and #1037 but I have not checked for those.

Obligatory gif:
https://imgur.com/a/WdmHUcX

### Approach
I worked together with foma in order to resolve this issue, with some additional background gained through my attempt to fix #836. See that issue for some additional reading.

### Open Questions and Pre-Merge TODOs

- [x]  I read the contribution guidelines and the wiki.
- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  This PR does not include files without the specific need to do so.
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in the editor
- [x]  This PR has been tested in a standalone build
- [ ]  This PR has been tested in multiplayer

### Notes:
The camera might not seem to center on the player, but that is due to the camera being offset by the chat window.

2018-05-15 22:15 UTC, DooblyNoobly commented
When the camera size changes then the camera needs to be recentered. There is a function somewhere that does it when the right panel is resized. See if you can find it and call that function straight after the resizing.

2018-05-15 22:21 UTC, fomalsd commented
Yeah, and also consider changing zoom positions to 1,2,3,4,5,8 or something like that, no way anyone's going to use 16x, while 3x is native zoom for 1080p

2018-05-15 22:27 UTC, fomalsd commented
Also did you check if/how it works in fullscreen? That ResponsiveUI was doing nasty things in fullscreen

2018-05-16 09:33 UTC, NinjaDanz3r commented
@fomalsd Latest commit tested in fullscreen on a standalone build, no noticeable errors on my end.

2018-05-16 09:53 UTC, fomalsd requested changes
Camera size should be updated every time window size is changed, currently it only happens on the setting change

2018-05-16 09:53 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/CameraZoomHandler.cs
> +			double ratio = Screen.height / (double) Screen.width;
Hm, what's the point of placing it in Update() if it's only getting changed via SetZoomLevel() anyway?
Why don't you convert this to Refresh() method that would recalculate camera size based on updated window size and just use this.zoomLevel ?

2018-05-16 09:53 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/CameraZoomHandler.cs
> +	private int cachedZoomLevel = 1;
I don't think you'll need this after all, read below

2018-05-16 09:53 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/CameraZoomHandler.cs
> +	public void SetZoomLevel(float zoomLevel)
Looks like this never gets triggered on resolution change, why not make this method only change this.zoomLevel, and Refresh() afterwards?

2018-05-16 13:09 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/CameraZoomHandler.cs
> +                double ratio = Screen.height / (double) Screen.width;
You don't need this logic here anymore :) just keep the last 2 lines of this method, Refresh() should have all the logic including zoom level check and text updates. Other than that, it looks fine!

2018-05-16 17:58 UTC, fomalsd approved these changes
Code is wonderful! 
However when checking it out I found that I still can't maximize window to fullscreen – ResponsiveUI resets it to windowed mode, so it does not fix #836 and #1037 at the moment. 
Still going to merge it as it gives pixel perfect results at any custom resolution in builds, well done!

2018-05-16 18:03 UTC, merged