NukeOps Setup
unitystation/unitystation pull request #1169
Opened 2018-08-08 07:21 UTC by dapocalypse

### Purpose
Fixes #972 

NukeOps is not set up. This PR sets up the nuke ops gamemode.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer

### Notes:
Paypal: dedhiadev5@gmail.com
B: 100

2018-08-08 15:50 UTC, dapocalypse commented
This is WIP until I say otherwise.

2018-08-15 03:12 UTC, DooblyNoobly requested changes
Needs a lot of work. There is no EscapeShuttle component that controls the movement of the shuttle serverside to escape. There is also a lot of unnecessary changes in this PR. You are getting better but you still need a bit more experience. I would suggest tackling a simplier problem first before attempting something as complex as trying to automate EscapeShuttle arrival.

A lot of files were included in this PR that didn't need to be there:
UnityProject/ProjectSettings/UnityConnectSettings.asset
UnityProject/Assets/Plugins/Facepunch.Steamworks/Facepunch.Steamworks.dll.mdb
UnityProject/Assets/Scenes/Lobby.unity
UnityProject/Assets/Scenes/OutpostDeathmatch.unity
UnityProject/Assets/Scripts/Editor/Tools/SearchandDestroy.cs
UnityProject/Assets/Scripts/Managers/New Prefab.prefab
UnityProject/Assets/Scripts/Managers/New Prefab.prefab.meta

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Editor/Tools/SearchandDestroy.cs
> +								// PrefabUtility.ReplacePrefab(cast, PrefabUtility.GetCorrespondingObjectFromSource(cast), ReplacePrefabOptions.ConnectToPrefab);
why?

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Food/FoodBehaviour.cs
> -	[Header("Being used for TDM")] public int healAmount;
So food no longer heals? We don't have any medical supplies in yet

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Health/Living/PlayerHealth.cs
> -				}
We should leave the killer name stuff, we still want to know who killed who

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Health/Living/PlayerHealth.cs
> -						else
There doesn't seem to be any attempt here to attribute a kill to either NukeOps or the Station crew. Instead you have just removed all the reporting code

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/PlayGroups/PlayerNetworkActions.cs
> -		playerHealth.StopBleeding();
There was no requirement to remove this

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Shuttles/MatrixMove.cs
> +public class DualFloatEvent : UnityEvent<float, float> { }
Oh dear god. I'm not reading this diff. Unsure of what you have changed here.

2018-08-15 03:12 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/Managers/MatrixManager.cs
> +    }
What was changed here? I'm not reading through the diff to find out as it was reformatted

2018-08-15 03:57 UTC, dapocalypse commented on UnityProject/Assets/Scripts/Editor/Tools/SearchandDestroy.cs
> +								// PrefabUtility.ReplacePrefab(cast, PrefabUtility.GetCorrespondingObjectFromSource(cast), ReplacePrefabOptions.ConnectToPrefab);
This caused an error.

2018-09-03 07:39 UTC, closed without merging