Right click radial menu! [Work in progress]
unitystation/unitystation pull request #1262
Opened 2018-09-28 00:53 UTC by Bod9001

### Purpose
Right click radial menu 
For all your clicking needs
### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [no]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [It brings up warnings but I haven't had time to correct them]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### Notes:
Still work in progress

2018-09-30 08:15 UTC, DooblyNoobly commented
--------------
You will need to remove the Right click canvas object from the managers tree. 
![image](https://user-images.githubusercontent.com/20813925/46255061-fb6e6c80-c4db-11e8-8bda-4de7582ff7c7.png)
Pull it out and work on it separately like that. 

You will also need to think about how it will be loaded and where. You can either put it in the hierarchy (outside of managers tree) in each game scene and save the scene. Or you can have a manager instantiate it at the start of any game scene by checking GameData if the newly loaded scene is an ingame scene or lobby scene. 

So I'd recommend instantiating it on the Managers.SetScreenForGame() method:
https://github.com/unitystation/unitystation/blob/bae12986d682021a19d46a9a1834810023cec1be/UnityProject/Assets/Scripts/Managers/Managers.cs#L42

Just after the Await call. (Don't put it in the isServer condition)

That way you don't have to submit a scene file in your PR and you will know whenever someone creates a new map that they don't have to worry about dragging in RightClickMenu prefab to their scene and saving it

---------------------

I'm still reviewing the rest. Will update comments as I go over the next day or so

2018-10-01 04:05 UTC, DooblyNoobly requested changes
Some small changes and I think we can merge this. Please see my comments too about instantiating the right click handler on InGame scenes.

2018-10-01 04:05 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +using UnityEngine;
two of the same using statements. Remove one

2018-10-01 04:05 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +		ins = this;
Everytime a scene loads you will have static instances of this class being created. That means after the scene has been destroyed, static instances from the last round still remain. You will have memory stack increases over time as the instances pile up. You need to check in awake if the instance has already been assigned and if it has then to destroy the instance that is doing the checking. Like this:

```cs
void Awake(){
    if(ins == null){
        ins = this;
    } else {
       Destroy(this);
    }
}
```
This will clean up any static instances of an object from the previous scene

2018-10-01 04:05 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +		SpriteDictionary ["Drag_Hand"] = Resources.Load<Sprite> ("UI/RightClickButtonIcon/" + "Drag_Hand");
A better way would be to make public Sprite fields on this class and drag the sprites into the inspector then save the prefab. What you have done is fine though as it only happens once on the start of the scene. So leave it if you want.

2018-10-01 04:05 UTC, DooblyNoobly commented on UnityProject/Assets/Scripts/UI/Right click/RadialMenuSpawner.cs
> +	void Awake(){
See below about the need to check if the instance has already been assigned.

i.e. static instances need to be set up like this:
```cs
void Awake(){
    if(ins == null){
        ins = this;
    } else {
       Destroy(this);
    }
}
```

2018-10-01 07:57 UTC, fomalsd reviewed
Looks good code wise apart from what Doobly suggested and sometimes weird naming

2018-10-01 07:57 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +public class contextMethod : Attribute
Please rename `contextMethod` to `ContextMethod`, classes are meant to be PascalCase

2018-10-01 07:57 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +			ItemAttributes Nameues = objects[i].GetComponent<ItemAttributes>();
Nameues? what's that? :)

2018-10-01 20:08 UTC, Bod9001 commented on UnityProject/Assets/Scripts/UI/Right click/Rightclick.cs
> +		SpriteDictionary ["Drag_Hand"] = Resources.Load<Sprite> ("UI/RightClickButtonIcon/" + "Drag_Hand");
yeah, it should be fine Because to the engine it's basically the same thing

2018-10-01 20:09 UTC, Bod9001 commented
The changes should be made?

2018-10-01 20:51 UTC, Bod9001 commented
you can Technically ignore all the changes to  the Scenes but I don't know how to do that?

2018-10-01 23:15 UTC, merged