Mining
unitystation/unitystation pull request #1297
Opened 2018-10-10 12:36 UTC by NicholasM10

### Purpose
Implements #1291, adds 6 asteroids for use in mining (tiny, very small, small, medium, large, very large - each with their tilemaps) and gives them random matrixmove position on round start.

They all have their own matrixmove, as updated on "station" prefab by Dooby. (I think)

Thanks to Foma and Doobly for help with different stuff.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### Notes:
On minimap, asteroids show up as shuttles with their icon because thats how matrixmove is recognised, I will try to fix this up in a bit, feel free to merge this though, if it looks good.

2018-10-10 13:08 UTC, fomalsd requested changes

2018-10-10 13:08 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +		SpawnNearStation();
`if (isServer)` goes here, also you should really check it in multiplayer: it might accidentally execute before matrices are initialized

2018-10-10 13:08 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +		if (isServer)
[Server] method won't run on clients anyway, checking after it's already executing is useless

2018-10-10 13:08 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +			mm.SetPosition(Random.insideUnitCircle * asteroidDistance + new Vector2(distanceFromStation, -distanceFromStation));
This won't work:
That `Vector2(distanceFromStation, -distanceFromStation)` is actually **always** Vector2( x=175; y=-175 ),
which equals to bottom right
So it doesn't guarantee that it won't spawn inside station, as first part can generate -175; 175 and asteroid will land exactly at the station, so please test your calculations before PRing!
What you need to do is exclude the entire range of ( x=-175..175; y=-175..175 ) from final randomised position by per-axis `Mathf.Clamp`ing or something else

2018-10-10 13:31 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +			mm.SetPosition(Random.insideUnitCircle * asteroidDistance + new Vector2(distanceFromStation, -distanceFromStation));
Also it would be nice if asteroids had random rotation on start

2018-10-10 13:32 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +			mm.SetPosition(Random.insideUnitCircle * asteroidDistance + new Vector2(distanceFromStation, -distanceFromStation));
...And some could be moving very slowly

2018-10-11 22:51 UTC, NicholasM10 commented
Okay, I think I've fixed everything that was mentioned here and on Discord, except the issue where asteroid tiles are showing up on screen at spawn for a frame.

I'd give a random guess that it might have something to do with the fact that my new functions are still being called on game startup rather than player spawn, so matrix move might be acting weird because of that?

2018-10-11 22:52 UTC, NicholasM10 commented
Oh and I also added random orientations for asteroids, good suggestion ^^

2018-10-12 02:36 UTC, merged

2018-10-12 06:15 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +		mm.SetPosition(clampVal);
You forgot about Y axis

2018-10-12 06:27 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +		int rand = Random.Range(0, 3);
`Note that max is exclusive for integers, so using Random.Range( 0, 10 ) will return values between 0 and 9`
It will never rotate left in your case

2018-10-12 06:27 UTC, fomalsd commented on UnityProject/Assets/Scripts/Map/Asteroid.cs
> +	IEnumerator DelayedStart()
Delaying is a pretty dirty way, it will lead to inconsistent behaviour and bad bugs on slower machines, don't do that!