Linux workflow fixes
unitystation/unitystation pull request #1556
Opened 2019-02-15 08:11 UTC by hecksadecimal

### Purpose
Attempting to work on the project in the Linux Unity Editor has been a troubling task for a variety of different reasons. 

1. SunVox, for some strange reason, causes the editor to crash when SunVox.sv_deinit() is called in a linux environment.

2. Additionally, when importing the project in unity for the first time it makes sweeping changes to a lot of .meta files.

This PR addresses both of these problems via the following changes: 

1. SunVox.sv_deinit() is altered with a preprocessor to avoid the crash in the Linux Unity Editor while leaving the call unaltered in full builds. 

2. A script has been added that when used will go through all the changed .meta files and perform a `git update-index --assume-unchanged` on them. This prevents git commit pollution with unintentional merging of altered .meta files

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer

### Notes:

Additionally, a `using static` directive was added to Synth.cs to fix VSCode intellisense and codelense not being able to locate the reference.

2019-02-15 08:15 UTC, hecksadecimal commented
I would appreciate if someone could test this PR in a Windows or macOS environment to ensure my changes don't break anything in those systems.

2019-02-15 09:12 UTC, Jibbajabbafic commented
What changes are shown on the meta files when you do a git diff? It could just be permissions getting changed. If that's the case I'd recommend setting the filemode setting to false instead since meta file changes can be important

2019-02-15 09:24 UTC, hecksadecimal commented
It isn't just permissions unfortunately. The editor makes actual changes to the contents of the file. Here's an example diff of `UnityProject/Assets/Textures/Turf/walls.meta b/UnityProject/Assets/Textures/Turf/walls.meta` Which represents a full deletion of the .meta file that the editor wanted to perform.

```
@@ -1,9 +0,0 @@
-fileFormatVersion: 2
-guid: ed3ef2eb89e34c46aee258b42550d970
-folderAsset: yes
-timeCreated: 1477562706
-licenseType: Pro
-DefaultImporter:
-  userData: 
-  assetBundleName: 
-  assetBundleVariant: 
```
And here's one which is modified rather than deleted.
`UnityProject/Assets/Textures/Turf.meta`

```
@@ -1,8 +1,6 @@
 fileFormatVersion: 2
-guid: 042cc493bdd7b414c88e586a1234b4ff
+guid: c29d2d460db5b73d39101afd46d6e7dc
 folderAsset: yes
-timeCreated: 1509379128
-licenseType: Free
 DefaultImporter:
   externalObjects: {}
   userData:
```

As you can see, the Linux Unity Editor has a habit of changing meta GUIDs among other things on import.

2019-02-15 11:43 UTC, krille90 commented
```
#if UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX
  private const string LIBRARY_NAME = "sunvox";
#elif UNITY_EDITOR_LINUX || UNITY_STANDALONE_LINUX
  private const string LIBRARY_NAME = "sunvox";
#elif UNITY_EDITOR_WINDOWS || UNITY_STANDALONE_WINDOWS || UNITY_STANDALONE_WIN
  private const string LIBRARY_NAME = "sunvox";
#elif UNITY_STANDALONE_LINUX
  private const string LIBRARY_NAME = "sunvox";
```

Couldn't this be shortened?

2019-02-15 11:52 UTC, hecksadecimal commented
It probably could be shortened, but as it was a list like that before I touched it to add the Linux entries changing it to shorten may be beyond the intended scope of this PR.

My only intention was to add fixes to make some crashes go away in the Linux editor and help prevent automatic .meta changes from poisoning commits.

2019-02-15 11:56 UTC, Jibbajabbafic requested changes
Only minor nitpicks, but I won't be able to test it today unfortunately.

2019-02-15 11:56 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sound/SunVox.cs
>  #elif UNITY_STANDALONE_LINUX
This bit won't be needed anymore (line 54) since it's covered by the elif you added

2019-02-15 11:56 UTC, Jibbajabbafic commented on assume_unchanged.sh
> +
This file would be better off in a dedicated scripts directory so it doesn't clutter the top level

2019-02-15 11:57 UTC, Jibbajabbafic commented
> ```
> #if UNITY_EDITOR_OSX || UNITY_STANDALONE_OSX
>   private const string LIBRARY_NAME = "sunvox";
> #elif UNITY_EDITOR_LINUX || UNITY_STANDALONE_LINUX
>   private const string LIBRARY_NAME = "sunvox";
> #elif UNITY_EDITOR_WINDOWS || UNITY_STANDALONE_WINDOWS || UNITY_STANDALONE_WIN
>   private const string LIBRARY_NAME = "sunvox";
> #elif UNITY_STANDALONE_LINUX
>   private const string LIBRARY_NAME = "sunvox";
> ```
> Couldn't this be shortened? (It always just the same name)

Agreed, most of this seems unnecessary

2019-02-15 12:02 UTC, fomalsd commented
That `assume_unchanged` could backfire, I suggest using separate changelists and just keeping unnecessary files there. You might want to commit some of them eventually.

![default](https://user-images.githubusercontent.com/10403536/52855365-13f0c380-3119-11e9-9fa4-5ce8ca446023.png)

2019-02-15 12:03 UTC, hecksadecimal commented
@Jibbajabbafic I made the changes you requested, but should I also refactor the whole #if #elif block to cut down on the entries in this PR?

2019-02-15 12:07 UTC, hecksadecimal commented
@fomalsd Changelists? I'm using VSCode, isn't that an IntelliJ Idea feature?

2019-02-15 12:10 UTC, fomalsd commented
I think GUI git clients should have this feature? but yeah, that screenshot is from Rider

2019-02-15 12:13 UTC, hecksadecimal commented
Never used a git GUI, I've always worked with CLI. In the event I do want to apply a change to an asset .meta I intentionally changed, I can just manually `git update-index --no-assume-unchanged` on it to be able to commit it.

2019-02-15 12:19 UTC, fomalsd commented
Ok, it's your call, feel free to keep that script in

2019-02-15 12:35 UTC, fomalsd approved these changes
No side effects on win10

2019-02-16 13:31 UTC, krille90 commented
> @Jibbajabbafic I made the changes you requested, but should I also refactor the whole #if #elif block to cut down on the entries in this PR?

Yea, I would prefer that.

2019-02-16 13:50 UTC, hecksadecimal commented
@krille90 How's that? Works just as well on my system and it really cuts down on how many entries there is.

2019-02-17 21:01 UTC, merged