Variable Speed support for player
unitystation/unitystation pull request #1575
Opened 2019-02-20 10:36 UTC by fomalsd

### Purpose
Fixes #1507 and #1572 
![heavygif](https://files.catbox.moe/14x0p0.gif)
Adds soft crit (player is able to crawl and whisper)
Adds ability to come out of crit (i.e. from oxygen damage):
![gif](https://user-images.githubusercontent.com/10403536/53085163-2f354780-34fa-11e9-95f2-b6bf8710c907.gif)

### Open Questions and Pre-Merge TODOs

- [ ]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [ ]  My code is indented with tabs and not spaces
- [ ]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [ ]  This PR does not bring up any new compile errors
- [ ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### Notes:
Player in softcrit still might be able to do something extra he's not supposed to...

2019-02-20 21:09 UTC, Jibbajabbafic approved these changes
Very nice, I have some small nitpicks but I'll leave it to you if you want to change anything

I noticed some bugs but I think they might be unrelated

2019-02-20 21:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs
> +		OnConsciousStateChange( proposedState );
Could this be put in the ConsciousState set method? That way people won't forget to call OnConsciousStateChange (unless there are cases where you want to update ConsciousState without calling it).

2019-02-20 21:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Objects/PushPull.cs
> +		return Pushable.SpeedClient;
Nice

2019-02-20 21:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Player/PlayerMove.cs
> +	[FormerlySerializedAs( "speed" )]
That's really handy!

2019-02-20 21:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs
> +				DropItem("rightHand");
How come DropItem is called twice?

2019-02-20 21:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs
> +		ForceRotation rotation = gameObject.GetComponent<ForceRotation>();
Could cache the rotation since it's being used elsewhere and I imagine falling will happen multiple times in a round

2019-02-20 21:15 UTC, Jibbajabbafic commented
Btw, could we change it to run by default on spawn?

2019-02-20 21:46 UTC, Jibbajabbafic requested changes
Ok did some more testing and there are a few bugs with crawling and pulling. 
- ~~The crawling player's position doesn't get updated until they reach the tile which can have some strange effects, such as blood appearing on a tile before they reach it~~ Already noted in #1566
- Crawling player can push a standing one lol
- If another player pulls a crawling player, crawling doesn't break the pull properly. You can crawl really far away and position doesn't get updated for ages. Then if the pulling player does move, the crawling person slowly moves to where they should be. Example: https://imgur.com/a/pINpoq0 
- Guns stop working on host client
- Make run the default option on spawn

I think the lerp for viewers needs to be kept fast, and it should only appear slow for yourself.

2019-02-21 08:12 UTC, fomalsd commented on UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs
> +				DropItem("rightHand");
oops, looks like an overlooked merge

2019-02-21 08:13 UTC, fomalsd commented on UnityProject/Assets/Scripts/Player/PlayerNetworkActions.cs
> +		ForceRotation rotation = gameObject.GetComponent<ForceRotation>();
I'll leave it as is so that @chairbender could swap it with his solution after it's merged

2019-02-21 08:14 UTC, fomalsd commented
> Btw, could we change it to run by default on spawn?

will do, but I must admit that running feels way too fast after walking for some time

2019-02-21 08:19 UTC, fomalsd commented
>     * If another player pulls a crawling player, crawling doesn't break the pull properly. You can crawl really far away and position doesn't get updated for ages. Then if the pulling player does move, the crawling person slowly moves to where they should be. Example: https://imgur.com/a/pINpoq0
Look at the wallmounts, you must have started editor with black fonts. no wonder game is messed up. 
I'll try to reproduce your issue anyway, but it might just be a messed up build on your side

2019-02-21 09:01 UTC, fomalsd commented on UnityProject/Assets/Scripts/Health/Living/LivingHealthBehaviour.cs
> +		OnConsciousStateChange( proposedState );
yep, good idea!

2019-02-21 09:49 UTC, fomalsd commented
Reproduced crawling player not breaking pull, good catch!

2019-02-21 10:59 UTC, fomalsd commented
Thanks for **proper** testing! it's all done now and ready for re-review

2019-02-22 19:25 UTC, Jibbajabbafic approved these changes

2019-02-22 19:26 UTC, Jibbajabbafic commented
Not getting those bugs anymore, nice work 👍

2019-02-22 19:26 UTC, merged