Flickering wall items
unitystation/unitystation pull request #1605
Opened 2019-03-04 04:39 UTC by coolcat1711

Implemented solution to issue #1571 by preventing use of the HiddenPos for position calculations

### Purpose
Fixes #1571 
Uses parent ObjectBehavior to set valid position.

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

### Notes:
PR creates a "lastNonHiddenPosition" that is used to rectify intermittent transform.position sets to the HiddenPos when the position is updated after exiting a locker.

2019-03-04 07:23 UTC, DooblyNoobly commented
I'll ask foma to look at this one, I'm not too familiar with playersync

2019-03-04 07:51 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/ObjectBehaviour.cs
> +	private readonly Vector3Int HiddenPos = new Vector3Int(0, 0, -100);
Just use TransformState.HiddenPos, no need to declare it in more than one place

2019-03-04 07:53 UTC, fomalsd commented
Did you test if push/pull and space interactions still work properly? And a high ping multiplayer test is a must when messing with player positions:
[Ping Simulation](https://github.com/unitystation/unitystation/wiki/Building-And-Testing#set-up-ping-simulation)

2019-03-04 09:19 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/WallmountSpriteBehavior.cs
> +		objectBehaviour = PlayerManager.LocalPlayer.GetComponent<ObjectBehaviour>();
This code won't compile, you forgot to define a variable.
But most importantly you **really** don't want to call `GetComponent` for each wallmount every frame!
instead refer to local player script where there's already a reference to PushPull (and ObjectBehaviour is its subclass)
So just access it instead and don't forget to change `pushPull` field type in PlayerScript to ObjectBehaviour as well
```suggestion
				var objectBehaviour = PlayerManager.LocalPlayerScript.pushPull;
```

2019-03-04 09:20 UTC, fomalsd requested changes
The code doesn't compile as is, but it seems to work with suggested changes (see above)

2019-03-05 00:34 UTC, coolcat1711 commented
Updated with suggested changes

2019-03-05 09:01 UTC, fomalsd commented
cool, good job!

2019-03-05 09:01 UTC, fomalsd approved these changes

2019-03-05 09:02 UTC, merged