Disabled mid-round job changes fixes #1614
unitystation/unitystation pull request #1646
Opened 2019-03-16 06:17 UTC by Scrando

### Purpose
ControlDisplays now ensures that the job select window is inactive at the start of the round. 
Added fallback to ensure that only one of either the job select window or team select window can be visible at one time and only if the player doesn't already have a job.

### Open Questions and Pre-Merge TODOs

- [x ]  This fix is tested on the same branch it is PR'ed to.
- [x ]  I correctly commented my code
- [x ]  My code is indented with tabs and not spaces
- [x ]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x ]  This PR does not bring up any new compile errors
- [x ]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer

2019-03-16 10:43 UTC, fomalsd commented
that's nice, but doesn't solve the issue if someone modifies client to always show player job selection window. 
the most important part security wise is: you need to validate such requests on serverside, and reject if player already has a job

2019-03-16 20:27 UTC, Scrando commented
Assuming JoinedViewer is serverside this should fix that.

2019-03-17 17:39 UTC, fomalsd commented
We have PlayerList to keep track of players and their occupations, use it instead

2019-03-18 09:16 UTC, fomalsd requested changes
Use serverside PlayerList instance instead and check if given ConnectedPlayer has a job other than None

2019-03-19 22:05 UTC, DooblyNoobly commented
@Scrando do you have an ETA on when you can look at the requested changes?

2019-03-20 07:44 UTC, Scrando commented
Sorry, been extremely busy. I can probably get it done Friday or Monday. If someone else is vying to fix this I can remove this pull request

2019-03-27 07:15 UTC, fomalsd commented
any updates?

2019-04-10 05:57 UTC, closed without merging

2019-04-10 05:58 UTC, Scrando commented
Sorry, got incredibly busy with final projects and now finals. Someone else should take this over