Adds canUse() in InputTrigger, for Interact() calls
unitystation/unitystation pull request #1681
Opened 2019-03-27 10:52 UTC by Aranclanos

### Purpose
Adds canUse() to InputTrigger, to handle range and mob status checks of Interact() calls, for both client and then server. Vendors and tiles interactions will now use it, fixing their issues with infinite range
Fixes #1652

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
Eventually all items should be using canUse() for their Interact()
The logic of canUse() is similar to canUseTopic() in the byond version of ss13 to handle href links

2019-03-27 11:47 UTC, fomalsd requested changes
I like this idea! just needs a couple of tweaks

2019-03-27 11:47 UTC, fomalsd commented on UnityProject/Assets/Scripts/Input System/Triggers/InputTrigger.cs
> +    public bool canUse(GameObject originator, string hand, Vector3 position, bool allowSoftCrit){
I'd set a default value for softcrit, also please rename method to PascalCase, it's not java
```suggestion
    public bool CanUse(GameObject originator, string hand, Vector3 position, bool allowSoftCrit = false){
```

2019-03-27 11:47 UTC, fomalsd commented on UnityProject/Assets/Scripts/Input System/Triggers/InputTrigger.cs
> +        if ((playerScript.canNotInteract() && (allowSoftCrit && !playerScript.playerHealth.IsSoftCrit)))
did you test this clause in different scenarios? feel like something is wrong here, perhaps you meant something like this:
```suggestion
        if ( playerScript.canNotInteract() && (!playerScript.playerHealth.IsSoftCrit || !allowSoftCrit) )
```

2019-03-27 11:47 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/VendorTrigger.cs
> +        return true;
please adjust your IDE to use tabs and not spaces!

2019-03-28 02:44 UTC, Aranclanos commented
Done

2019-03-28 13:27 UTC, fomalsd approved these changes

2019-03-30 10:47 UTC, fomalsd commented
![wallmountsinteract 2019-03-30 13_40_41](https://user-images.githubusercontent.com/10403536/55275078-d2476100-52f1-11e9-8088-86f9358c5d7a.gif) simple wallmounts with MessageOnInteract (+ extinguisher cabinet) still work out of range

2019-03-30 10:48 UTC, fomalsd requested changes
please fix range check for wallmounts

2019-03-31 23:04 UTC, Aranclanos commented
There are around 50 different Interact() that should be reviewed honestly

2019-04-01 22:52 UTC, Aranclanos commented
`		if(!CanUse(originator, hand, position, false)){
			return false;
		}
		if(!isServer){
			return true;
		}
`
At the end the check ended up like this, I'm not convinced but I needed it to avoid doubleclicking and not blocking the current Update because you clicked on something out of reach. For now I'd like to finish it here and in the future take a look again, maybe adding the check in InputTrigger instead.
Oh and adding a serverside clickspam check.

2019-04-01 23:06 UTC, Aranclanos commented
And the idea would be making Interact() a void and making the 'interacted' check a variable that would be accessed in CanUse() or something like that

2019-04-04 07:17 UTC, fomalsd approved these changes

2019-04-04 07:21 UTC, fomalsd commented
Works, very nice!

2019-04-04 07:21 UTC, merged