New Shuttle UI + Fixes #1327
unitystation/unitystation pull request #1702
Opened 2019-04-05 20:12 UTC by kaffo

* Added Fuel Bar (Credit to Foma for the image)
  * Exposed API to set the % fuel remaining for when fuel gets
  implemented
  * Should be scalable/moveable and not break
* Added Coordinates
  * Uses parent MatrixMove to update position from server
* Reworked shuttle UI
  * Used fewer fonts/tried to use similar sizes
  * Moved the shuttle movement controls to the right
  * Much smaller buttons
  * Fixed background on radar
* Bonus UI swap script for Nanotransen vs other agencies
  * Set the UI type on the MatrixMove script and see the UI change

### Purpose
This PR is to fix #1327 
Credit to @fomalsd for his fuel gauge
Let me know if there's anything you want to change, it's pretty simple stuff

### Open Questions and Pre-Merge TODOs

- [x]  This fix is tested on the same branch it is PR'ed to.
- [x]  I correctly commented my code
- [x]  My code is indented with tabs and not spaces
- [x]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [x]  This PR does not bring up any new compile errors
- [x]  This PR has been tested in editor
- [x]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
Picture of the UI:
![image](https://user-images.githubusercontent.com/1458225/55653757-65e3ca80-57e7-11e9-90e3-ee2d32424740.png)

2019-04-06 12:50 UTC, fomalsd requested changes
<img width="624" alt="Scr 2019-04-06 в 15 43 31" src="https://user-images.githubusercontent.com/10403536/55669671-e1468a00-5882-11e9-9181-412d3f43af69.png">

 - don't see the fuel gauge, sprite is white
 - coordinates don't work, at least on syndie shuttle. always shows 100,100
 - disclaimer still says "property of nanotraNsen" on syndie ship
 - you didn't commit meta files for your added scripts and textures. do it!

2019-04-06 12:50 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/Shuttles/GUI_FuelGauge.cs
> +			Logger.LogError("No Fuel Gauge Set on Shuttle!");
```suggestion
			Logger.LogError("No Fuel Gauge Set on Shuttle!", Category.UI);
```

2019-04-06 12:50 UTC, fomalsd commented on UnityProject/Assets/Scripts/UI/Shuttles/GUI_CoordReadout.cs
> +			Logger.LogError("Coord Readout not setup correctly!");
```suggestion
			Logger.LogError("Coord Readout not setup correctly!", Category.UI);
```

2019-04-06 19:53 UTC, kaffo commented
I resetted my branch and tried it clean and it seems to work with what I've got commited now. So hopefully it should be good now

2019-04-06 22:20 UTC, fomalsd approved these changes

2019-04-06 22:21 UTC, fomalsd commented
all good now, minor thing is that elements look too small now (text is kinda hard to read)
<img width="1440" alt="Scr 2019-04-07 в 1 19 52" src="https://user-images.githubusercontent.com/10403536/55675971-6194db80-58d3-11e9-9000-401ea64ef3ba.png">

2019-04-07 12:49 UTC, fomalsd commented
yep, sizes are good now!

2019-04-07 12:49 UTC, merged