Girders and wall construction
unitystation/unitystation pull request #1758
Opened 2019-04-18 01:18 UTC by Aranclanos

### Purpose
Fixes #1726
Adds girders, players will now be able to build them using metal on their hand, and finish the process of wall building by applying more metal on the girder.

Reduces the amount of metal sheets spawned by disassembling walls to two.
Adds the structures png with only the sprite girder created.

Moves DisappearObject() from Grenade code to InputTrigger and PickUpTrigger.
Adds a new prefab for girders.
Adds MetalTrigger.cs and GirderTrigger.cs

![image](https://user-images.githubusercontent.com/701959/56330314-e72f4b80-615d-11e9-9521-16bd95cdb777.png)

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients, if applicable)

### Notes:
the girders only work serverside only, CanUse() is broken in develop at the moment

2019-04-18 02:47 UTC, chairbender commented
Re: CanUse being broken (sorry for the spam but posting this here as well for visibility)

@Aranclanos

I wouldn't call it broken. The only change I made was that it no longer has the side effect of sending an interaction message to the server when it is invoked on the client side. I removed this behavior because it doesn't make sense to have a method called "CanUse" which has a quite significant and undocumented side effect of performing network communication - the method was doing too much by having this side effect. CanUse should only be used to check if something is usable.

Please refactor your code to send this message in a different way.

In the meantime I will work on the other users of this method to ensure they do the same thing.

2019-04-18 03:07 UTC, chairbender commented
FYI @Aranclanos I just merged a fix for this problem for all the other users of CanUse. Take a look at that if you're unsure how to send the message now. PR was #1759

2019-04-18 14:57 UTC, Aranclanos commented
Done

2019-04-20 04:50 UTC, chairbender commented
Wow, really nice! Tested it out and it seems fine. Going over the code now...

2019-04-20 04:52 UTC, chairbender requested changes
just want to get some comments describing those new classes, other than that looks good

2019-04-20 04:52 UTC, chairbender commented on UnityProject/Assets/Scripts/Items/MetalTrigger.cs
> +public class MetalTrigger : PickUpTrigger
please add /// comment describing the component

2019-04-20 04:52 UTC, chairbender commented on UnityProject/Assets/Scripts/Objects/GirderTrigger.cs
> +public class GirderTrigger : InputTrigger
please add /// comment describing the component

2019-04-23 01:43 UTC, DooblyNoobly commented
Let me know once the comments are added and I'll resolve these conflicts

2019-04-23 02:28 UTC, Aranclanos commented
Done

2019-04-23 05:06 UTC, DooblyNoobly commented
thanks for fixing the conflicts too!

2019-04-23 05:10 UTC, merged