Fix Deconstruct Request using incorrect reach distance test.
unitystation/unitystation pull request #1875
Opened 2019-05-17 17:24 UTC by VitrescentTortoise

### Purpose
Deconstruct request used an incorrect distance check to verify if tile could be deconstructed. Fixed to use PlayerScript.IsInReach.  #1799

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

2019-05-17 22:13 UTC, fomalsd requested changes
proposed a safer approach

2019-05-17 22:13 UTC, fomalsd commented on UnityProject/Assets/Scripts/Construction/Managers/Deconstruction.cs
> +		if (PlayerScript.IsInReach(player.transform.position, worldCellPos) == false)
transform.position/localPosition aren’t good references for player or items/objects. they can represent out of date positions or not work properly across different matrices.
```suggestion
		if (player.Player().Script.IsInReach(worldCellPos, true) == false)
```
This one uses RegisterTile under the hood, so it’s fine to use

2019-05-17 22:25 UTC, VitrescentTortoise commented
> 
> 
> proposed a safer approach

I see, did not know that. Looks like I used the wrong IsInReach instead of the one suggested. Thank you, I committed it.

2019-05-20 15:28 UTC, fomalsd approved these changes

2019-05-20 15:29 UTC, merged