Fix flying objects like glass shards getting stuck on player
unitystation/unitystation pull request #1881
Opened 2019-05-19 23:30 UTC by VitrescentTortoise

### Purpose
Floating objects over a speed threshold will now damage what is in their path, and continue floating. They are no longer stopped by the player, and do not spam damage until player is dead. This
fixes #1865.

There is room for more complexity in this system (perhaps changing momentum of flying objects), or 
handling heavy objects differently (knock down player?). This is not related to the bug.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Changes that may have incurred side effects:
I removed the prerequisite for OnHit requiring object to have been thrown to do damage. Fast flying objects that were moved with space wind or other pushing forces should not need to be thrown to do damage. This should allow for emergent damage behavior instead of having to manually fake the throw data. This is only usage of OnHit, so shouldn't affect anything else at the moment.

I removed that !IsPlayerNearby check because I do not believe it makes sense. In practice, it would make no difference because it was OR'd with registerTile.IsPassible which currently always returns true. It seems this code intended to allow an object to drift into a solid object if no players are around. No idea what this is about.

2019-05-20 16:07 UTC, fomalsd commented
Loving it! 
![GIF](https://user-images.githubusercontent.com/10403536/58035752-fa488900-7b18-11e9-9bc3-f1845d40b70a.gif)
Yeah, I can't remember why `IsPlayerNearby` was there. 
Very smooth experience so far, we'll tweak it later if something comes up

2019-05-20 16:16 UTC, fomalsd commented
Oh, looks like I found something:
![GIF](https://user-images.githubusercontent.com/10403536/58036209-1698f580-7b1a-11e9-8074-004f17580d22.gif)
So items actually no longer stop when flying through player, at all. Need to figure out a way to differentiate stop/no stop situations

2019-05-20 16:23 UTC, fomalsd requested changes
Flying items still need to stop when hitting player in some scenarios (like when thrown by other player), perhaps when thrownBy isn't null? 
Or maybe adding a special passThrough flag to ThrowInfo that would be true for push-induced collisions...

2019-05-26 17:01 UTC, fomalsd commented
any updates?
IMO two most viable options so far are:
1) single algo – if thrown from afar: stop on tile adjacent to player and hurt him
When thrown from adjacent tile: hurt and go through
(downside is double damage)
2) adding a special `passThrough` flag to ThrowInfo that would be true for wind push-induced collisions, and process things differently depending on that flag

2019-05-26 20:16 UTC, VitrescentTortoise commented
Moving into a new apartment atm, so might be a few days before I have time for next iteration.

2019-06-04 14:38 UTC, fomalsd commented
It would be really nice if you figured it out soon, as items actively punching player sound very annoying

2019-06-06 00:42 UTC, VitrescentTortoise commented
I apologize for starting this and not wrapping it up, a lot of my free time has recently evaporated. All are welcome to pull my changes and pick up where I left off. I'd tell you I'll get back to it soon but don't want to make any promises I can't keep.

2019-06-11 09:03 UTC, DooblyNoobly commented
@fomalsd where does the wind push stuff actually happen where we could set a passThrough flag on ThrowInfo? Right now I can't see where wind push uses any of the throwinfo stuff.

2019-06-11 09:29 UTC, fomalsd commented
Wind push is done here:
https://github.com/Aranclanos/unitystation/blob/442b440e0238cad6f399e51fe431aba9eb4fc000/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/ReactionManager.cs#L53-L73
initial idea was that sliding (not flying) objects don't harm player, but they get in the air again if speed is high enough

2019-06-12 07:54 UTC, closed without merging