Make ignore more restrictive
unitystation/unitystation pull request #1883
Opened 2019-05-20 03:20 UTC by lfricken

### Purpose
Prevent more binary files from getting committed and stop blowing up GitHub after building.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [X]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [X]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
None

2019-05-20 15:42 UTC, fomalsd reviewed
hm, not sure about zip... we might need that eventually
also I've added binary stuff before, namely SunVox for all supported platforms, and who knows if we want to add something else

2019-05-20 17:27 UTC, lfricken commented
A binary type can always be removed later just as easily though.

2019-05-21 10:40 UTC, DooblyNoobly requested changes

2019-05-21 10:40 UTC, DooblyNoobly commented on .gitignore
> +*.dll
Not really keen on gitignoring dll libs as there is a possibility of using appropriately licensed libs of that type in the assets. Everything else is fine

2019-05-29 10:38 UTC, fomalsd commented
any updates?

2019-06-07 14:34 UTC, fomalsd commented
Closed due to inactivity, create a new PR if you want to try again

2019-06-07 14:34 UTC, closed without merging