Pipenets
unitystation/unitystation pull request #1884
Opened 2019-05-21 20:38 UTC by Aranclanos

### Purpose
Adds a WIP pipenet system, with two new objects, pipes and connectors.

### Open Questions and Pre-Merge TODOs

- [X]  This fix is tested on the same branch it is PR'ed to.
- [ ]  I correctly commented my code
- [X]  My code is indented with tabs and not spaces
- [X]  This PR does not include any unnecessary .meta, .prefab or .unity (scene) changes
- [X]  This PR does not bring up any new compile errors
- [X]  This PR has been tested in editor
- [ ]  This PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)

### Notes:
Known issues:
-pipes get sucked/pushed by environmental air
-cant rotate pipes
-all pipes are north/south
-advanced pipes (vents, scrubbers, connectors) connect both sides even if their sprite is for south
-pipe sprites go over canisters
-canisters have no sprite to indicate the connection to the connector
-canisters can be pushed or pulled when connected
-pipes can be pulled while anchored
-map lacks pipes, vents and scrubbers don't spawn anchored
-no comments
-clients don't update pipe sprites
-there's nothing to check for a shuttle moving/rotating
-there are some debug variables

2019-05-21 23:07 UTC, fomalsd requested changes
Not gonna lie, I lol'd about these named fields pretty hard
Check out other comments, there are a few important points

2019-05-21 23:07 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/Pipenets/Pipe.cs
> +	public int ARANpipenetmembers;
lol, why would you add your nickname to field names?

2019-05-21 23:07 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Objects/AirVent.cs
> +			metaDataLayer.UpdateSystemsAt(Vector3Int.RoundToInt(transform.position));
You're using `transform.position` *everywhere*. **Don't!** Instead, cache a reference to RegisterTile in Pipe class and use `registerTile.WorldPositionServer`, they're already rounded and reliable. transform.position is clientside fluff, never rely on it if you have RegisterTile.

2019-05-21 23:07 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/Pipenets/Pipe.cs
> +	public enum Direction
you can use powerful `Orientation` struct, by the way

2019-05-21 23:07 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/Pipenets/Pipe.cs
> +		transform.position = Vector3Int.RoundToInt(transform.position);
Do they still get blown away by wind? You could take advantage of `IsTileSnap` and `isNotPushable` bools, making sure they can't be blown away or nudged (and snap to tile like lockers and players)

2019-05-21 23:08 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Objects/AirVent.cs
> +			metaDataLayer.UpdateSystemsAt(Vector3Int.RoundToInt(transform.position));
<img width="846" alt="Scr 2019-05-17 в 10 18 12" src="https://user-images.githubusercontent.com/10403536/58136364-78e71880-7c36-11e9-9e1a-fd9ef21cbaac.png">

2019-05-22 12:28 UTC, Aranclanos commented
if possible id like to have this merged fix the known issues on different PRs so its more organised and easier to review

2019-05-22 12:32 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/Canister.cs
> +				var foundConnectors = MatrixManager.GetAt<Connector>(registerTile.PositionServer, true);
MatrixManager works with World positions only – it iterates through all matrices (And `Matrix` class is for local positions), use `WorldPositionServer` here

2019-05-22 12:36 UTC, fomalsd commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/Meta/Atmospherics/Pipenets/Pipe.cs
> +	public List<Vector3Int> GetAdjacentTurfs()
this looks redundant, `MetaUtils.GetNeighbors()` probably does what you need

2019-05-22 12:39 UTC, fomalsd commented
other than that it's ok to merge

2019-05-22 13:43 UTC, Aranclanos commented
Done

2019-05-22 13:51 UTC, fomalsd approved these changes

2019-05-22 13:53 UTC, merged