Window knocking
unitystation/unitystation pull request #2497
Opened 2019-12-29 16:34 UTC by Bod9001

### Purpose
Fixes #2469
and some auto format
### Notes:
 I've had to Change CmdRequestMeleeAttack  to Except the intent
so There might be some funny Behaviours caused because of this

This could be implemented in a better way but no one said anything about it on Discord so I went ahead with it

### Please make sure you have followed the self checks below before submitting a PR:

Tested in editor
Will test in build, editor Multiplayer
Renamed functions to appropriate names

2019-12-30 20:24 UTC, chairbender commented
@Bod9001 this isn't quite the right way to do this as far as the interaction logic is concerned.  This is a tile interaction, so it should use the Tile Interaction system: https://github.com/unitystation/unitystation/wiki/Implementing-Interactions#how-can-i-create-tile-interactions

This ticket shouldn't require changing the CmdRequestMeleeAttack or TilemapDamage. All that should be needed is to 
  * modify Meleeable, moving LayerType.Windows into harmIntentOnlyAttackbleLayers so you'll only bash windows on harm intent
  * Create a new TileInteraction SO which performs the tapping validation / logic and add it to the Window tile asset's tileInteractions field.

There shouldn't be any other changes than that (except the ones related to sound manager)

2019-12-30 20:28 UTC, chairbender requested changes
@Bod9001 this isn't quite the right way to do this as far as the interaction logic is concerned.  This is a tile interaction, so it should use the Tile Interaction system: https://github.com/unitystation/unitystation/wiki/Implementing-Interactions#how-can-i-create-tile-interactions

This ticket shouldn't require changing the CmdRequestMeleeAttack or TilemapDamage. All that should be needed is to 
  * modify Meleeable, moving LayerType.Windows into harmIntentOnlyAttackbleLayers so you'll only bash windows on harm intent
  * Create a new TileInteraction SO which performs the tapping validation / logic and add it to the Window tile asset's tileInteractions field.

There shouldn't be any other changes than that (except the ones related to sound manager)

2019-12-31 00:09 UTC, Bod9001 commented
All fixed up

2019-12-31 01:04 UTC, chairbender requested changes
Wow didn't take you long to figure out and fix. Had an issue with missing script error probably due to the naming of the window knock, also added an interaction message for it. See my PR: https://github.com/Bod9001/unitystation/pull/4

Once that's merged it's good to merge.

2019-12-31 01:04 UTC, chairbender commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/TilemapDamage.cs
Are there any changes in this file other than formatting changes? Looks like only formatting changes, which is fine.

2019-12-31 11:21 UTC, Bod9001 commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/TilemapDamage.cs
yeah, Probably is because I copied it over from the raw on github to reverse the changes I did

2019-12-31 11:23 UTC, Bod9001 commented
yeah the Hard part is finding the right systems to use 99% of the time : P

2019-12-31 19:43 UTC, merged