New version number, better fullscreen and self-hiding disclaimer
unitystation/unitystation pull request #2601
Opened 2020-01-14 17:59 UTC by daalta

### Purpose
![Unity_2020-01-14_18-56-58](https://user-images.githubusercontent.com/9169275/72369177-d832f500-36ff-11ea-8200-6f6982a18892.png)
![2020-01-14_18-58-38](https://user-images.githubusercontent.com/9169275/72369201-e1bc5d00-36ff-11ea-87b8-fcd53250914a.png)
* The alpha disclaimer introduced in https://github.com/unitystation/unitystation/pull/2587 now self-hides when entering a game.
  * It hides if any scene is loaded that is not the lobby. The disclaimer is shown again when opening the escape menu.
* The build number text was changed and is now always displayed in the bottom-left of the screen.
  * This should be useful when looking at screenshots. We'll be able to tell what version of Unitystation is shown in feedback, community posts, bug reports etc.
* Added a new fullscreen option to the options menu.
  * Entering fullscreen sets the game resolution to the screen's native resolution. 
  * Exiting fullscreen defaults to a 1280 * 720 resolution.
  * Fullscreen- and resolution settings are automatically stored by Unity. Exiting the game *should* restore the previous settings.
  * This makes https://github.com/unitystation/unitystation/issues/2575 less of an issue. ALT+ENTER still sets the wrong resolution, but using the new menu option works file.
    * We could (should?) disable ALT+ENTER to enter fullscreen. However, this would mean that players cannot enter or exit fullscreen without joining a game.

### Notes

Pressing escape no longer exits fullscreen. (See https://github.com/unitystation/unitystation/issues/2575#issuecomment-574277144) I am not sure why that functionality was there, but looks like I did not break anything? 🤞

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor

2020-01-14 19:53 UTC, daalta commented
Doobly has some upcoming UIManager changes, so don't merge this until his changes are in. Then I'll resolve any conflicts.

2020-01-16 17:56 UTC, daalta commented
Finally done with merging develop into my branch, this is ready for review. Had some issues - probably due to removed, renamed or conflicting files. We'll never knoooow 🌬

2020-01-16 22:07 UTC, Jibbajabbafic requested changes
Everything else seems good, thanks!

2020-01-16 22:07 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/UI/IngameMenu/GUI_IngameMenu.cs
> +		SceneManager.sceneLoaded += OnSceneLoaded;
Make sure you add a corresponding OnDisable() to unregister this method or there could be issues in the future

2020-01-16 22:28 UTC, DooblyNoobly commented
Looks really good. Just fix up the points noted by jibby and we'll merge it

2020-01-16 23:05 UTC, DooblyNoobly commented
actually I'll fix this up in my pr. Merging now

2020-01-16 23:05 UTC, merged

2020-01-17 23:04 UTC, daalta commented
Thanks @Jibbajabbafic and @DooblyNoobly doobly, appreciate it!

Fullscreen could still be a little more robust, but it should do for now.