Adds False Walls and False Reinforced Walls
unitystation/unitystation pull request #3370
Opened 2020-02-27 01:48 UTC by Robustin

Description:

False walls! The cornerstone of any stealthy antagonist. The behavior is identical to how false walls functioned on /tg/code, including the massive headache of getting it to smooth with nearby walls.

This also resolves a bug where GeneralDoorAnimator.cs would break any door that used less than 6 frames for animation and it adds "Non-Automatic" door behavior that can be used for mineral doors and other unpowered doors that don't simply open from being bumped. It also adds a "isHighlightable" object trait that prevents highlighting of objects when false. 

_Now with a branch that isn't FUBAR'd_

This is a bounty (#2358).

Remaining Work:

- Figure out why removing a passable wall tile is deleting atmos

- The sprite atlas has been giving me problems when I pull to a clean branch, need to confirm all issues are resolved there.

2020-02-27 02:05 UTC, Evan-R-Rogers commented
Please tell me you added it to the tile palette for doors?

2020-02-27 02:30 UTC, Robustin commented
I asked in the last PR for clarification on that. It has its sprites kept with the other "General Door Animation" doors.

2020-02-27 02:34 UTC, Evan-R-Rogers commented
This link should help ya: [bwoink](https://unitystation.github.io/unitystation/development/How-to-Map/#edit-a-palette)

2020-02-27 02:42 UTC, corp-0 commented
that commit history, I felt the pain.

2020-02-27 16:15 UTC, Robustin commented
@Evan-R-Rogers 

From what I've been able to deduce, it wouldn't be proper for me to add this to the Tile Palette. It's classified as a "door" and we do not seem to use the tile palette for doors (the doors category on the tile palette is literally empty). It's a prefab object like all the other doors.

2020-02-27 18:03 UTC, fomalsd requested changes
looks like metafiles are gitignored in resources/icons, since all textures are supposed to be stored outside of Resources folder anyway, but doors might be a special case unaccounted for. yet that metafile is crucial for this whole thing to work:
[metal_fwall_closing.png.meta.txt](https://github.com/unitystation/unitystation/files/4263207/metal_fwall_closing.png.meta.txt)
other than that it's great

2020-02-27 18:03 UTC, fomalsd commented on UnityProject/Assets/Scripts/Doors/DoorController.cs
> +		}
DisappearFromWorld server doesn't despawn prefab but moves it to hiddenpos forever. that and #1902 probably make that nasty no pressure effect when combined.
use this:
```suggestion
        public void ServerDisassemble(HandApply interaction)
        {
            tileChangeManager.RemoveTile(registerTile.LocalPositionServer, LayerType.Walls);
            Spawn.ServerPrefab(CommonPrefabs.Instance.Metal, registerTile.WorldPositionServer, count: 4);
            Despawn.ServerSingle(gameObject);
        }
```
but! keep in mind that if false wall will be destroyed due to shooting, `            tileChangeManager.RemoveTile(registerTile.LocalPositionServer, LayerType.Walls);` won't be called, see https://github.com/unitystation/unitystation/blob/26339d2153e59fbed87b06fe43bf438a8ab1ccb1/UnityProject/Assets/Scripts/Tilemaps/Behaviours/Objects/RegisterDoor.cs#L52-L57

2020-02-27 18:17 UTC, fomalsd commented
also could you please readd this script I deleted earlier today (to Scripts/Editor/Tools)
https://gist.github.com/fomalsd/90d5916e1375c2771669405c9c14e68d

2020-02-27 22:34 UTC, Robustin commented
@fomalsd 

The last commit addressed the remaining issues. 

I re-added the tool in #3394. I'll see if I have time to pull this onto a clean branch for another round of testing. Was there any other problems you noticed?

2020-02-28 05:43 UTC, fomalsd reviewed
use of transform.position is discouraged since it can be inaccurate. always try to use registerTile position for objects
will playtest again later today and see if I can find any quirks

2020-02-28 05:43 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/Construction/Girder.cs
> +		tileChangeManager.UpdateTile(Vector3Int.RoundToInt(transform.localPosition), falseTile);
```suggestion
		tileChangeManager.UpdateTile(registerObject.LocalPositionServer, falseTile);
```

2020-02-28 05:43 UTC, fomalsd commented on UnityProject/Assets/Scripts/Objects/Construction/Girder.cs
> +		tileChangeManager.UpdateTile(Vector3Int.RoundToInt(transform.localPosition), falseTile);
```suggestion
		tileChangeManager.UpdateTile(registerObject.LocalPositionServer, falseTile);
```

2020-02-28 10:40 UTC, fomalsd reviewed
it's all good gameplay wise, just apply suggested changes and I'll merge this

2020-02-28 15:07 UTC, Robustin commented
Oh you can commit suggestions now, neat.

2020-02-28 17:36 UTC, fomalsd approved these changes
awesome

2020-02-28 17:36 UTC, merged

2020-03-01 22:06 UTC, DooblyNoobly commented
@Robustin can you pm me your paypal email on discord pls