Usable Sprite Animation System - Simple World Icons [DNM]
unitystation/unitystation pull request #3469
Opened 2020-03-03 01:15 UTC by dapocalypse

### Purpose
Fixes #2590 

### Notes:
_Please enter any other relevant information here_

### Please make sure you have followed the self checks below before submitting a PR:

- Code is sufficiently commented
- Code is indented with tabs and not spaces
- The PR does not include any unnecessary .meta, .prefab or <b>.unity (scene) changes</b>
- The PR does not bring up any new compile errors
- The PR has been tested in editor
- Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

2020-03-03 01:16 UTC, dapocalypse commented
Do Not Merge, I'm having this here so that I can get feedback on what I'm doing, its WIP.

2020-03-08 03:57 UTC, dapocalypse commented
No longer Do Not Merge

2020-03-08 16:49 UTC, dapocalypse commented
I think this fixes #2311 now that im looking at them

2020-03-09 10:37 UTC, RedlineTriad requested changes
I don't think you can have constructor parameters for `MonoBehaviour`s and if you don't use `Start()` and `Update()` you should probably remove it.

2020-03-09 14:09 UTC, Jibbajabbafic requested changes
This doesn't fix #2311 since that's an epic which is broken down into multiple smaller issues which still need implementing. This is a good start but it still has a long way to go before it's a fully usable system. 

This isn't gonna be an easy task and it's gonna take a lot of work. I think you should start with the subtasks in #2311 if you're serious about completing the whole thing.

Edit: looks like this was supposed to fix #2590, but it still needs to handle networking and be implemented on some items

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationHandler.cs
> +	#region Server
This logic will probably be running on the client not the server, so I don't think this is appropriate

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationHandler.cs
> +	public void Animator(AnimationInfo anim, SpriteRenderer spriteRenderer)
Change the name of this to match the class name so it's a proper constructor: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/constructors

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationHandler.cs
> +				coroutine = WaitAndShow(1 / FPS, spriteRenderer, anim, i);
Coroutines are expensive, so it would be better if you created a single one which loops through all of the frames instead of creating a new coroutine per frame.

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationHandler.cs
> +    }
Don't include empty functions if they don't do anything

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationInfo.cs
> +public class AnimationInfo : MonoBehaviour
This class would be better off as a ScriptableObject. Have a look at the guidance in #2311 and try to follow it's advice.

2020-03-09 14:09 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationInfo.cs
> +	}
I'm not sure if we would need to create custom animations at runtime. They should all be setup in the editor (similar to something like ItemAttributes) and then loaded/changed out as needed. 
For example, you would make an 'on' animation and an 'off' animation in the editor, and then at runtime in the code you can switch the animation when the welder is activated or deactivated.

2020-03-09 14:13 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Sprite Handler/AnimationHandler.cs
> +	public void Animator(AnimationInfo anim, SpriteRenderer spriteRenderer)
Actually nevermind this, MBs can't have constructors.

2020-03-12 10:40 UTC, closed without merging