adds a new speech modifier system
unitystation/unitystation pull request #3824
Opened 2020-04-03 22:59 UTC by corp-0

# Pull Request Template

### Purpose
This PR will implement a system to handle speech modifiers (this is anything that will modify the text player input as speech). 

![](https://cdn.discordapp.com/attachments/312454684021620736/695706304953581579/unknown.png)

Contributors can create their own speech modifiers with ease, no code required in most common cases, and assign them to the SpeechModManager so they can work ingame.

![](https://cdn.discordapp.com/attachments/312454684021620736/695677568187236452/unknown.png)

![](https://cdn.discordapp.com/attachments/312454684021620736/695753303329341460/unknown.png)

In case the contributor needs some control over his modifier, he can inherit from CustomSpeechModifier and implement the required method. Now he just have to assign the custom code in the SpeechModifierSO customCode field.

These modifiers will work on both chat log and chat bubble and won't exclude each other, so you can have a stuttering Italian cook.

### Note
I added a new field in character customization, "Accent". This field is intended as a temporal thing so people can play around with the modifiers until we have a proper character trait system.

![unknown](https://user-images.githubusercontent.com/43683714/78411270-86ef1f00-75e5-11ea-9226-32043f203374.png)

### Please make sure you have followed the self checks below before submitting a PR:

- [x] Code is sufficiently commented
- [x] Code is indented with tabs and not spaces
- [x] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [x] The PR does not bring up any new compile errors
- [x] The PR has been tested in editor
- [x] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [x] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [x] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [x] The PR has been tested with round restarts.
- The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

2020-04-04 00:07 UTC, corp-0 commented
test failed after 7 minutes. I suspect github actions broke

2020-04-04 09:52 UTC, Macoron commented
Try merge master to your PR - should fix tests

2020-04-04 09:56 UTC, RedlineTriad commented
Don't merge master, my PR with failing tests just got merged.

2020-04-04 18:51 UTC, corp-0 commented
fuck yes, on the green again. Can someone review code and destroy my selfsteem now?

2020-04-04 19:05 UTC, RedlineTriad requested changes

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Resources/ScriptableObjects/Speech/CustomMods/Stuttering.cs
> +    public override string ProcessMessage(string message)
Use tabs instead of spaces.

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chat/Chat.Process.cs
> +		switch (sentByPlayer.Script.characterSettings.Speech)
What about using a dictionary?

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (LetterReplaceList.Count != 0)
```suggestion
		if (LetterReplaceList.Count > 0)
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (WordReplaceList.Count != 0)
```suggestion
		if (WordReplaceList.Count > 0)
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> + 	public List<StringListOfStrings> WordReplaceList = new List<StringListOfStrings>();
```suggestion
 	[SerializeField] private List<StringListOfStrings> wordReplaceList;
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +	public List<StringListOfStrings> LetterReplaceList = new List<StringListOfStrings>();
```suggestion
	[SerializeField] private List<StringListOfStrings> letterReplaceList;
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +	public List<string> Beginning = new List<string>();
```suggestion
	[SerializeField] private List<string> beginning;
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +	public List<string> Ending = new List<string>();
```suggestion
	[SerializeField] private List<string> ending;
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		   if (Beginning.Count != 0)
```suggestion
		   if (Beginning.Count > 0)
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		   if (Ending.Count != 0)
```suggestion
		   if (Ending.Count > 0)
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +	}
```suggestion
	bool WasYelling(string message) => message == message.ToUpper();
```

2020-04-04 19:05 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (customCode != null) return customCode.ProcessMessage(message);
```suggestion
		if (customCode != null) 
		{
			return customCode.ProcessMessage(message);
		}
```
Always use curly braces and new lines.

2020-04-04 19:07 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (LetterReplaceList.Count != 0)
honest question, what would be the benefit?

2020-04-04 19:09 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (LetterReplaceList.Count != 0)
Intention is more clear.

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Resources/ScriptableObjects/Speech/CustomMods/Stuttering.cs
> +    public override string ProcessMessage(string message)
done

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Scripts/Chat/Chat.Process.cs
> +		switch (sentByPlayer.Script.characterSettings.Speech)
done

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (LetterReplaceList.Count != 0)
done

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +		if (WordReplaceList.Count != 0)
done

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> + 	public List<StringListOfStrings> WordReplaceList = new List<StringListOfStrings>();
done

2020-04-05 02:27 UTC, corp-0 commented on UnityProject/Assets/Scripts/ScriptableObject/SpeechModifier.cs
> +	public List<StringListOfStrings> LetterReplaceList = new List<StringListOfStrings>();
done

2020-04-05 09:18 UTC, RedlineTriad approved these changes

2020-04-05 15:26 UTC, merged