Reagent Container refactoring and map updates
unitystation/unitystation pull request #3961
Opened 2020-04-19 18:49 UTC by Macoron

### Purpose
Reagent Container was 1k lines of code long with a lot of obsoleted code. This PR refactor it and more code comments. Some minor bugs were fixed in process.
All obsolete reagent containers prefabs was removed or replaced in all maps. Chemistry got variety of beakers, no more generic containers and "eatable" cups.

Also added cool attribute for Temperature. It can show temperature in Kelvin, Celsius or Fahrenheit in inspector.
<img width="381" alt="Снимок экрана 2020-04-19 в 19 09 28" src="https://user-images.githubusercontent.com/6161335/79696678-ed7f6880-8286-11ea-9854-0e916dccedd0.png"> 

### Fixed bugs:

- FillContainer now properly updates after last slurp in UI
- Fixed few bugs related to ReagentContainer.CurrentCapacity and excess
- Reagent transfer doesn't lead to mass loose anymore
- Small fixes of mop and bucket. You can't place mop inside chem dispenser anymore :(

2020-04-19 20:05 UTC, RedlineTriad requested changes
Since I don't have much time left today i will just make a summary:

1. You changed multiple files to spaces instead of tabs.
2. A setter shouldn't add, it should set.
3. Use `TryGetValue()` instead of `Contains()` and `[]`

2020-04-19 21:14 UTC, Macoron commented
Well, looks like chemistry tests executes fine in Editor, but fails on server. They also seems to fail in a weird pattern, but error doesn't seem to give any information.

Should set throws invalidkey exception if there is no such reagent in mix?

2020-04-20 10:46 UTC, DooblyNoobly commented
test fails:
```
2020-04-20T06:46:48.2607259Z Your script should either check if it is null or you should not destroy the object.]]></message>
2020-04-20T06:46:48.2607609Z                   <stack-trace><![CDATA[  at (wrapper managed-to-native) UnityEngine.Object.GetName(UnityEngine.Object)
2020-04-20T06:46:48.2607996Z   at UnityEngine.Object.get_name () [0x00001] in /home/builduser/buildslave/unity/build/Runtime/Export/Scripting/UnityEngineObject.bindings.cs:189 
2020-04-20T06:46:48.2608217Z   at Chemistry.Reagent.get_Name () [0x00000] in /github/workspace/UnityProject/Assets/Scripts/Chemistry/Reagent.cs:20 
2020-04-20T06:46:48.2608355Z   at Chemistry.Reagent.ToString () [0x00001] in /github/workspace/UnityProject/Assets/Scripts/Chemistry/Reagent.cs:26 
2020-04-20T06:46:48.2608503Z   at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x002b1] in <437ba245d8404784b9fbab9b439ac908>:0 
2020-04-20T06:46:48.2608841Z   at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args) [0x00023] in <437ba245d8404784b9fbab9b439ac908>:0 
2020-04-20T06:46:48.2609342Z   at System.String.Format (System.String format, System.Object arg0) [0x00008] in <437ba245d8404784b9fbab9b439ac908>:0 
2020-04-20T06:46:48.2609882Z   at Tests.Chemistry.ReactionContainerFixture.AssertContainerContentsEqualTo (Chemistry.Components.ReagentContainer contain
```

You'll have to redo your mapping changes as I will be merging some shortly

2020-04-21 20:06 UTC, corp-0 commented
last test failed without any information on why. I had the same problem and after a push it went green. We should repeat tests.

2020-04-22 17:14 UTC, Bod9001 commented
could you see if you could move the map updates, and just push the reagent containers changes?

2020-04-23 20:11 UTC, Macoron commented
Alright, all set and fixed. @RedlineTriad can you please validate changes?

2020-04-24 15:13 UTC, RedlineTriad requested changes

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/Reaction.cs
>  			}
You can probably change this to a ReagentMix instead of adding multiple times.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/Reaction.cs
>  			}
Same here.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/ReagentMix.cs
> +				return reagents[reagent];
You can use `TryGetValue()` instead.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/ReagentMix.cs
> +			var curAmount = reagents[reagent];
Use `TryGetValue()` instead.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/ReagentMix.cs
> +
Is this needed? you shouldn't need to know about the keys and you can use `reagentMix[reagent]` instead.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Items/Others/FireExtinguisher.cs
>  public class FireExtinguisher : NetworkBehaviour, IServerSpawn,
This uses spaces instead of tabs.

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Tilemaps/Editor/GeneratePlantSOs.cs
> +using Chemistry.Components;
This probably isn't needed?

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Util/Independent/TemperatureUtils.cs
> +			ret = FromKelvin(t, to);
Always use `{}`

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Util/Independent/TextUtils.cs
> +            return "transparent";
use `{}`

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Util/Independent/TextUtils.cs
> +        }
Use `{}`

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Util/Independent/TextUtils.cs
> +            nearestColor = "dark " + nearestColor;
Use `{}`

2020-04-24 15:13 UTC, RedlineTriad commented on UnityProject/Assets/Resources/Prefabs/Items/Electricity/Single Medium Cable Coil.prefab
> -      value: 2
Why have changes here?

2020-04-24 15:33 UTC, Macoron commented
Well, get more merge conflicts. Guess I better close this PR for good.
Maybe add parts of it next time

2020-05-03 15:36 UTC, Macoron commented
@RedlineTriad resurrected this PR, fixed all merge conflicts and code style errors. All map changes were reverted.

2020-05-03 15:38 UTC, PetMudstone commented
Bad time to reopen this PR. No one is allowed to make .prefab changes at the moment because Doobly and Chairbender, maybe some others, are working on Subscenes. Check #4131.

2020-05-03 15:43 UTC, Macoron commented
Not a big deal. This PR can wait until .prefab lockdown is over. Prefab conflicts should be easily fixed.

2020-05-03 22:31 UTC, DooblyNoobly commented
DNM added until lockdown is lifted. Can you rebase and resolve the conflicts then

2020-05-08 15:21 UTC, ThatDan123 commented
Lockdown is over.

2020-05-08 20:20 UTC, corp-0 commented
only two conflicts away

2020-05-09 11:13 UTC, Bod9001 commented
ok, Since it been open so long I'm going to merge it

2020-05-09 11:13 UTC, merged