Firelocks
unitystation/unitystation pull request #4041
Opened 2020-04-25 23:21 UTC by Aranclanos

### Purpose
Adds firelocks!
They close on detecting low pressure on their tile or being damaged by a hotspot

### Please make sure you have followed the self checks below before submitting a PR:

- [X] Code is sufficiently commented
- [X] Code is indented with tabs and not spaces
- [X] The PR does not include any unnecessary .meta, .prefab or **.unity (scene) changes**
- [X] The PR does not bring up any new compile errors
- [X] The PR has been tested in editor
- [X] Any new files are named using PascalCase (to avoid issues on case sensitive file systems)
- [ ] Any new / changed components follow the [Component Development Checklist](https://github.com/unitystation/unitystation/wiki/Component-Development-Checklist)
- [ ] Any new objects / items follow the [Creating Items and Objects Guide](https://github.com/unitystation/unitystation/wiki/Creating-Items-and-Objects%3A-Now-With-Prefab-Variants) (especially concerning the use of prefab variants)
- [X] The PR has been tested in multiplayer (with 2 clients and late joiners, if applicable)
- [ ] The PR has been tested with round restarts.
- [ ] The PR has been tested on moving / rotating / rotated-before-joining matrices (if applicable)

2020-04-26 08:56 UTC, ThatDan123 commented
Missing reference found in scriptable object FireDoor field Object

  Expected: <empty>
  But was:  < (FireDoor, Object) >at Tests.MissingAssetReferences.CheckMissingRefenceFieldsScritpableObjects () [0x0016a] in /github/workspace/UnityProject/Assets/Tests/Asset/MissingAssetReferences.cs:172[Tests] Missing reference found in scriptable object FireDoor field Object

2020-04-27 02:55 UTC, Aranclanos commented
ok fixed!!! go team!!!

2020-04-27 12:10 UTC, Jibbajabbafic commented
One problem I've found is that the fire doors stop the bump interaction with doors underneath them:

![jtnlRbkdix](https://user-images.githubusercontent.com/4493127/80370610-66368400-8888-11ea-8e53-904cb6c6284a.gif)

2020-04-27 14:46 UTC, Jibbajabbafic requested changes
A few things:
- Make doors more sensitive to low pressure
- Add checks for high pressure
- Allow the doors on the same tile to be bumped regardless of the order they are place (e.g. if the fire lock is on top of the door it seems to work fine, but the other way round it stops working).
- Make the firelock prefab default to the open state to make it easier for mappers
- Check the tiles around the firelocks since they don't seem to help stop fires spreading much https://imgur.com/a/zjIWARV

2020-04-27 14:46 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Doors/FireLock.cs
> +			if (metaNode.GasMix.Pressure < AtmosConstants.MINIMUM_OXYGEN_PRESSURE)
The doors need to be more sensitive to pressure changes.

![Uj52N3CunD](https://user-images.githubusercontent.com/4493127/80377455-39d43500-8893-11ea-9c3e-acbc9965bef4.gif)


Try using this constant instead:
```suggestion
			if (metaNode.GasMix.Pressure < AtmosConstants.WARNING_LOW_PRESSURE)
```

2020-04-27 14:46 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Doors/FireLock.cs
> +			if (metaNode.GasMix.Pressure < AtmosConstants.MINIMUM_OXYGEN_PRESSURE)
I think it would be good if they also checked if it's greater than WARNING_HIGH_PRESSURE/HAZARD_HIGH_PRESSURE too.

2020-05-02 08:58 UTC, Aranclanos commented
Right so to avoid fires from rushing through faster than what the firelocks can close, I enabled the fire alarms so they have a hub to "report" a fire so all the firelocks linked to said alarm get closed, acting like a room. But it's under the mappers hands to add the firelocks to the alarm list.

The pressure check is also now under the alarm instead of all firelocks to avoid affecting performance hits and they're more sensible, easier to trigger.

2020-05-02 12:46 UTC, Jibbajabbafic requested changes
The fire locks are way better at stopping fires now!

![image](https://user-images.githubusercontent.com/4493127/80864519-1803f500-8c7b-11ea-9e5b-03ea938100d1.png)

One problem with the fire alarms is that they need to check the tile next to them in the direction that they are facing, otherwise they only check the atmos inside the wall.
![image](https://user-images.githubusercontent.com/4493127/80863507-da03d280-8c74-11ea-837b-ac2f1a0504ab.png)

The tests need to be fixed before I can merge this though, so delete all the existing fire alarms in outpost and pog and I can merge this before Doobly's prefab lockdown.

2020-05-02 12:46 UTC, Jibbajabbafic commented on UnityProject/Assets/Scripts/Objects/FireAlarm.cs
> +	*/
Delete this or add a comment explaining why it's commented out if you want to use it in future

2020-05-02 22:12 UTC, merged