Adds "Use Exact Amounts" option to Reactions
unitystation/unitystation pull request #4372
Opened 2020-06-07 07:48 UTC by MajorMoonjump

allows you to make reactions require exact amounts rather than ratios, as shown with the dough and cake batter recipes

also i'm back haha gottem

2020-06-07 11:17 UTC, vlandemart requested changes

2020-06-07 11:17 UTC, vlandemart commented on UnityProject/Assets/Scripts/Chemistry/Reaction.cs
> +			else if (useExactAmounts == true)
90% of this else is just copypaste of if statement
Can't you just insert
`if (useExactAmounts && !ingredients.All(ingredient => reagentMix[ingredient.Key] >= ingredient.Value))
    return;`
after if statement at line 41 not to make unneeded nesting?

2020-06-08 01:03 UTC, MajorMoonjump commented
I noticed that only after I already closed everything out, I'll fix it

2020-06-08 04:18 UTC, MajorMoonjump commented
alright, i did it

2020-06-08 09:11 UTC, ThatDan123 commented
![image](https://user-images.githubusercontent.com/56727168/84013052-51add700-a970-11ea-894a-9c0cec45ea1d.png)

I would suggest making the bool the first condition of the If statement just for performance reasons,  unless a code reviewer doesnt think that'll be necessary.

2020-06-08 19:10 UTC, RedlineTriad commented on UnityProject/Assets/Scripts/Chemistry/Reaction.cs
> +			}
This will use inexact amounts for when there is more of an ingredient than is strictly needed.

2020-06-08 20:23 UTC, Bod9001 commented
all good?

2020-06-08 20:24 UTC, MajorMoonjump commented
yep

2020-06-08 20:41 UTC, merged