Adds disposal stuff! Pipes, machines, pipe dispenser
unitystation/unitystation pull request #4524
Opened 2020-07-02 07:04 UTC by NoooneyDude

Adds disposal pipes, disposal machines and the pipe dispenser. Bored atmospheric technicians, rejoice!

![Disposals](https://user-images.githubusercontent.com/6926225/86322031-49566c80-bc8e-11ea-8b37-cbe2e3eb77a7.gif)

### Additions
* Adds disposal pipe objects, tiles (straight, bent, terminating, merging, splitting)
* Adds disposal bins, intakes, outlets
* Adds disposal pipe traversal logic
* Adds disposal manager to handle traversals
* Adds pipe dispenser, to dispense atmospherics and disposals components

> Disposal bin has a UI:
![Disposal Bin](https://i.imgur.com/rwEbcXM.png)
> Pipe dispenser has a UI:
![Pipe Dispenser](https://i.imgur.com/uR0C2GO.png)
> Disposal pipes and machines are mappable and de/constructable.

## Extras
* Tiles can now implement the IExaminable interface - useful for producing examine text from tile state logic.
* Tile interactions will now check each tile in the Underfloor layer, instead of only the first underfloor, for interactions.
* NetLabel NetUI component has new event for when the text changes.

### Notes:
> No mainstation scenes have been updated to reflect the additions.
> Mapping: if a disposal machine is not mapped over a disposal pipe terminal, it assume an uninstalled state.
> Disposal pipe adjacency is not currently cached.

2020-07-02 10:40 UTC, ReiderJack requested changes

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	bool stateSecuredStatus = true;
Rename variable to `isSecureStatus` or something which statrs with `is`.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	bool RequireFloorPlatingExposed = false;
Rename variable to use `is` in the beginningof the name.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	bool VerboseFloorExists()
Rename to use `Is` in the beginning.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	bool VerbosePlatingExposed()
Rename to use `Is` in the beginning.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	void Anchor()
Add `private`.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	void Unanchor()
Add `private`

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	void TryWrench()
You named it `Try` but it does not return if it succeeded. Rename it to just `Wrench` or return bool/why_failed and process that.

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Disposals/DisposalBin.cs
> +			void StoringPlayer()
Why this method here?

2020-07-02 10:40 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Disposals/DisposalMachine.cs
> +			if (MachineAnchored) SetMachineInstalled();
Use brackets please.

2020-07-02 10:41 UTC, ReiderJack commented
Add `private` where it's missing.

2020-07-10 06:10 UTC, merged

2020-12-28 13:26 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Construction/WrenchSecurable.cs
> +	void TryWrench()
Hmm, the "Try" prefix is because a wrench interaction isn't guaranteed at that point, but the caller doesn't care about the result.

2020-12-28 13:27 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Disposals/DisposalBin.cs
> +			void StoringPlayer()
The method should only be relevant to the enclosing method - should I move it out or convert to lambda?