Shuttle now doesn't sell people
unitystation/unitystation pull request #4822
Opened 2020-08-10 07:07 UTC by LukaErCaiman

'Edited the CargoShuttle script and separated its item scanner from the "UnloadCargo" function before attaching it to a public "SearchForObjectsOnShuttle" function that returns a Transform Object
-Added a "LifeformChecker" function in CargoManager that looks for any players or animals on the shuttle.
-Modified the "CallShuttle" function on CargoManager so that, using "LifeformChecker", it avoids flying off from the station with a player or animal.

### Purpose
Fixes the issue that allowed the cargo shuttle to fly off from the station with characters on board and erase them afterwards by preventing the shuttle from flying as long as any object that could be alive is aboard.
### Notes:
None

2020-08-10 12:36 UTC, ReiderJack requested changes

2020-08-10 12:36 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +	bool LifeformChecker()
Good rule is to call methods with a verb. In this case for example: `CheckLifeforms`

2020-08-10 12:36 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +	bool LifeformChecker()
Also we specify access modifiers. At least doing it lately. So please add `private`

2020-08-10 12:36 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (ObjectHolder.GetChild(i).GetComponent<LivingHealthBehaviour>() != null)
This is really expensive way to check if an object is a player. Did you try to check by layers?
<https://docs.unity3d.com/Manual/Layers.html> 
There is a Player layer.

2020-08-10 12:36 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (ObjectHolder.GetChild(i).GetComponent<LivingHealthBehaviour>() != null)
`if(((1<<gameObject.layer) & layers) == 0)` return `true`;
Where layers has Player layer. 
<https://docs.unity3d.com/ScriptReference/LayerMask.html>

2020-08-10 12:36 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (ObjectHolder.GetChild(i).GetComponent<LivingHealthBehaviour>() != null)
You can do ` LayerMask.GetMask("Player")`, but cache it before iterating in `for` to not call it everytime.

2020-08-10 12:50 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (ObjectHolder.GetChild(i).GetComponent<LivingHealthBehaviour>() != null)
Also you can iterate without using `for`
```
foreach (Transform child in transform)
{
  //child is your child transform
}
```

2020-08-10 16:00 UTC, corp-0 commented
@ReiderJack it is mimicking ss13 behavior. It doesn’t just check players but anything that has/had life.

2020-08-10 16:03 UTC, corp-0 commented
That being said, you can check player and NPC layer to get the same result.

2020-08-10 16:11 UTC, ReiderJack commented
But Ian has value and he can be sold

2020-08-10 16:12 UTC, corp-0 commented
In OG SS13 you can’t sell Ian not even dead mobs/players

2020-08-10 16:20 UTC, ReiderJack commented
I see the point in not selling alive players, but don't see one for mobs or dead bodies.

2020-08-10 16:47 UTC, corp-0 commented
Hiding bodies would be way too easy if you can just sell them.

2020-08-10 16:54 UTC, the-other-autumn commented
not to mention it deletes the player, meaning they cannot be revived with admin intervention at all

2020-08-10 16:55 UTC, ReiderJack commented
Just use layers to determine if there is a living thing on a matrix, not `GetComponent`

2020-08-11 07:31 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (child.transform.gameObject.layer == 12 || child.transform.gameObject.layer == 8)
Can't you just do `child.gameObject.layer`? Because `child` is already `transform`.

2020-08-11 07:31 UTC, ReiderJack commented on UnityProject/Assets/Scripts/Managers/CargoManager.cs
> +			if (child.transform.gameObject.layer == 12 || child.transform.gameObject.layer == 8)
Cache `LayerMask` before `foreach`
`LayerMask layersToCheck = LayerMask.GetMask("Player", "NPC")`

Then do the check `if((child.gameObject.laer & layersToCheck) == 0) continue`
`== 0` will check if it's false. *Or i might be wrong and it's `!= 0`*

2020-08-11 21:33 UTC, ReiderJack approved these changes

2020-08-11 21:34 UTC, merged