Fix broken electrical cable cutting window
unitystation/unitystation pull request #6466
Opened 2021-05-05 05:54 UTC by Korywon

### Purpose

Fixes #6458.

### Notes:

`cableCuttingWindowPrefab` was never assigned, which causes the `Instantiate()` call to raise an `ArgumentException`. This in turn breaks the cable cutting window from popping up, and ultimately results in the user being unable to cut electrical cables. Simply enough, the solution is to just load the resource. We ideally only want to do it once (hence the `null` check).

There are some other behaviors I want to work on, but since we're in a feature freeze, I'll hold it off for now.

### Changelog:

CL: Fixed cable cutting window not showing when cutting electrical cables

2021-05-05 06:20 UTC, Korywon commented
Do not merge yet. Going to implement the ability to cut single wires without the window as a QOL improvement.

2021-05-05 12:30 UTC, Aranclanos commented
afaik we're trying to stop using Resources.Load and other variants to remove assets from the resources folder

2021-05-05 16:10 UTC, Korywon commented
Good point. I'll see what I can do. Some people pointed towards the usage of the UIManager. I'll get that after I get the little QOL done.

2021-05-05 16:27 UTC, corp-0 commented
I don't get it, why downcast the reference?

2021-05-05 16:48 UTC, Korywon commented
Do you mean changing `cableCuttingWindowPrefab` from `CableCuttingWindow`  to `GameObject`? If so, it's because the reference is a prefab and the `CableCuttingWindow` class requires `RectTransform`. I'm assuming that the `RectTransform` is derived. I did try leaving the type as `CableCuttingWindow` but no joy.

2021-05-05 17:00 UTC, corp-0 commented
uhm, I think the instantiation of the object could be solved adding it to UIManager, like someone suggested you before. I wonder if there is a bettter pattern to follow when doing UI in unity.

2021-05-05 17:24 UTC, Korywon commented
Yeah there was mention of the UIManager starting to become a little too clustered.

![image](https://user-images.githubusercontent.com/22848944/117182687-493a6800-ad9c-11eb-8657-151ef849b6c4.png)

![image](https://user-images.githubusercontent.com/22848944/117182725-55262a00-ad9c-11eb-8b97-83ede76beda1.png)

Probably good enough to throw into UiManager for now, but going forward, we might want to rethink about the UI. Maybe even generalizing/standardizing UI so that we can dynamically create windows. Maybe even creating a script or some kind of toolkit so we don't have so many custom windows and prefabs. Something like how desktop apps use GTK/GDK or or web apps using component libraries.

Still learning the ins and outs of how UI is handled for both unity and the game, but I'm up for ideas.

2021-05-14 06:25 UTC, Korywon commented
Did some more work on this. Cleaned up quite a bit, added a LOT more documentation, and simplified/consolidated the logic into smaller, more manageable methods. Last step is to fix the scrollbar on the cable cutting window and cut if there's only one cable.

I think I'll create another issue to get the cable cutting window moved onto the UI manager. This PR is already big enough as it is.

2021-05-14 06:56 UTC, NoooneyDude commented
Superb efforts in documenting the code! Though, if I may, perhaps a little too far:

```
// Now, we loop through each electrical connection.
for (int i = 0; i < eConns.Count; i++)
```

Too many comments can make the code harder / take longer to read. Just a heads-up for next time ; )

2021-05-14 07:12 UTC, Korywon commented
Thanks! And fair point. That comment was placed there before I was able to untangle everything. There definitely is a fine balance.

Are there any other comments you found to be too obvious or not very useful?

2021-05-14 07:17 UTC, NoooneyDude commented
Sure. Here are a few more examples:
```
// First, make sure we actually found electrical connections.
if (eConns != null)
```
```
// If the tile we're looking at is a basic tile...
if (tile is BasicTile basicTile)
```
```
// If the the tile is something that's supposed to be underneath floors...
if (basicTile.LayerType == LayerType.Underfloor)
```
```
// Then we loop through each under floor layer in the matrix until we
// can find an interaction.
foreach (BasicTile underFloorTile in matrix.UnderFloorLayer.GetAllTilesByType<BasicTile>
```

If you think it's ready you can mark as ready. 

I have a suggestion for the tile interaction that you may or may not be interested in tackling, but I'll create a new issue for it.

2021-05-14 13:40 UTC, NoooneyDude commented
I can't wait for you to mark as ready - merging now!

2021-05-14 13:41 UTC, NoooneyDude requested changes

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Engineering/CableCoil.cs
> +		/// cables cannot cannot diagonally and no connections are illegal. All
```suggestion
		/// cables cannot connect diagonally and no connections are illegal. All
```

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Engineering/CableCoil.cs
> +		/// <param name="position">Position of the cell we're building thecable at.</param>
```suggestion
		/// <param name="position">Position of the cell we're building the cable at.</param>
```

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Engineering/CableCoil.cs
> +			if (wireEndA == Connection.Overlap | wireEndB == Connection.Overlap)
```suggestion
			if (wireEndA == Connection.Overlap || wireEndB == Connection.Overlap)
```

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Tilemaps/Behaviours/InteractableTiles.cs
> +	/// <returns></returns>
```suggestion
```

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Engineering/CableCoil.cs
> +		/// <param name="interaction"></param>
```suggestion
```

2021-05-14 13:41 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Engineering/CableCoil.cs
> +		/// <param name="interaction"></param>
```suggestion
```

2021-05-14 13:42 UTC, merged

2021-05-14 14:44 UTC, Korywon commented
Whoops, I was asleep around the time you suggested changes. Thanks for catching those typos! I was going to implement the single cable cutting feature, but that's alright. I'll open up another PR for it. :smile:

I'll take a look at the issue you popped up,

2021-05-14 14:48 UTC, Korywon commented
As a side note, did we change the way the actions work? I don't see my comments on the changelog.

2021-05-14 14:50 UTC, NoooneyDude commented
> As a side note, did we change the way the actions work? I don't see my comments on the changelog.

That's odd. I'm not sure myself why the changelog comments don't exist.

2021-05-14 14:55 UTC, Korywon commented
Oh, I think the actions were changed to `CL [type]: comment` rather than `CL: comment`. I changed my PR to fit that. Do you mind adding it to the CL if possible?