Better Drunk Shader and Camera Controls + New Desaturation Shader
unitystation/unitystation pull request #6832
Opened 2021-06-20 15:12 UTC by jamessimo

### Purpose
With Drug and Alcohol reagent processing being worked on it its about time we made the Drunk shader not place holder but a fully fleshed out. The drunk camera script now has direct control over the Sine and Cos wave length, duration and speed along with scaling light. This can be tweaked by any dev with the editor and/or C# code with no need to edit the shader directly. #6793

This also has fixed a nasty Linux visual bug that made the entire screen upside down, to counteract this I added in a check for DirectX 11 and flip the coordinates if so. 

### Notes:
Whiles all the controls for the drunk and desaturation shader are in, I did not hook these up to anything, that is for whoever is working on reagent consumption to do. #6400 See the CameraEffectControlScript for example about how you choose drunken level. Desaturation is just a value from 0 to 1.0. The shader code will force to 1 if you feed it a big number and 0 if you feed it a negative. 

There is also a TODO to find out why some shaders conflict, if you have more than one shader the screen still inverts, not sure why as some of these shaders do not use uv.y coords. Will investigate more. 

Also moved OSX/Mac to use OpenGL BEFORE metal, Metal is introducing bugs that we cannot fix so easier to put them on the same pipeline as Linux users. #4537 

### Changelog:

CL: **[Improvement]** Made the drunk view more tame like you are drunk and not tripping on antifreeze and mercury. 
CL: **[Fix]** Fixes the drunk shader being upside-down for OpenGL machines (Linux and some mac) #4542

2021-06-20 20:18 UTC, pyrosshade commented
why is the vomiting bounty linked?

2021-06-20 22:31 UTC, jamessimo commented
> why is the vomiting bounty linked?

Sorry was a mistake. Removed.

2021-06-21 14:20 UTC, ThatDan123 requested changes
You haven't changed the camera prefab only the online scene

2021-06-21 15:06 UTC, ThatDan123 approved these changes

2021-06-21 21:06 UTC, merged