Scaled human blood
unitystation/unitystation pull request #6861
Opened 2021-06-26 15:42 UTC by jamessimo

### Purpose
We need to scale up blood as right now a human only has 5u of blood and should have closer to 500

### Notes:
I have made this a draft as I need help understanding what else needs to be scaled up. No matter what I do nothing really seems to change and not sure if this is enough

2021-06-27 21:05 UTC, Bod9001 commented
need to change the code/SOs for metabolic reactions MetabolismReaction.cs BodyHealthEffect stuff like PercentageBloodOverdose
and increase heartbeat strength tho that needs to be balanced bit, 
increased lung strength maybe
BodyFat needs to be balanced
Stomach
change how much each body part stores in blood

2021-06-27 21:05 UTC, Bod9001 commented
Those are all I can think of currently

2021-07-11 11:38 UTC, Bod9001 commented
like, it would be nice to do the fat too, since the player gets slowed quite a lot by lack of nutrients and there's other stuff I've specified that hasn't been done, do you want me to merge then work on those?

2021-07-11 23:48 UTC, jamessimo commented
> , do you want me to merge then work on those?

If possible yes, I have tried many times to make fat remove the slow down but nothing I seem to do works.

2021-07-13 09:03 UTC, vlandemart requested changes
Changes are requested.
Some magic numbers (even though they were present before the PR), and few mistakes

2021-07-13 09:03 UTC, vlandemart commented on UnityProject/Assets/Scripts/Core/Factories/EffectsFactory.cs
> +		if (bloodReagents.Total < 5f)
These are magic numbers. Move them into separate public/[SerializedField] variable so they would be easier to change later on.

2021-07-13 09:03 UTC, vlandemart commented on UnityProject/Assets/Scripts/Core/Factories/EffectsFactory.cs
> +		else if(bloodReagents.Total > 5f && bloodReagents.Total < 15f)
Also a magic number

2021-07-13 09:03 UTC, vlandemart commented on UnityProject/Assets/Scripts/HealthV2/Living/CirculatorySystem/CirculatoryInfo/CirculatoryInfo.cs
> +	public float BLOOD_MAX = 700;
Can't those be changed in a prefab instead of a script?
If you are sure you need to change a script, please correct tooltips for those, right now "BLOOD_NORMAL = 500" but tooltip says "The normal amount of blood in the body. 5000mL is the human average"

2021-07-13 09:03 UTC, vlandemart commented on UnityProject/Assets/Scripts/HealthV2/Living/CirculatorySystem/CirculatorySystemBase.cs
> +			AddFreshBlood(ReadyBloodPool, 500);
This is a magic number. Please, add variable like "StartingBlood" and use it instead, so it would be easier to change later

2021-07-13 09:03 UTC, vlandemart commented on UnityProject/Assets/Scripts/Items/Medical/HealthScanner.cs
> +			var bloodPercent = Mathf.Round(bloodTotal / health.CirculatorySystem.BloodInfo.BLOOD_NORMAL * 1000);
Why "bloodTotal / bloodNormal * 1000" is a blood percent?
In ideal case, our bloodTotal == bloodNormal, so that "bloodTotal / bloodNormal" would be 1. If you multiply it by 100, you get percentage.

2021-07-14 14:34 UTC, jamessimo commented on UnityProject/Assets/Scripts/HealthV2/Living/CirculatorySystem/CirculatoryInfo/CirculatoryInfo.cs
> +	public float BLOOD_MAX = 700;
Ok fixed it in my latest

2021-07-14 15:35 UTC, merged