Regen meshs' stacks are now visually visible + require opening before use.
unitystation/unitystation pull request #8377
Opened 2022-02-16 19:43 UTC by MaxIsJoe

Title

2022-02-17 05:06 UTC, NoooneyDude requested changes
The code from the other PR (#8380) to require opening an edible (like soda can) is very similar to the code here. Therefore, that and this code here should be in a new component, say: `HandPreparable` or something.

In this PR, you would not create a new component that inherits from `HealsTheLiving` but rather add a `TryGetComponent()` within `HealsTheLiving` that checks for the `HandPreparable` component says it is ready for application.

In the edible PR: similar story, checking if that component says it is ready to eat.

Also, move the check to `WillInteract` if you want the interaction to propagate properly to the `HandPreparable` component. That is, the check to see if something is ready to eat / apply should be done in WillInteract (can't remember if required client-side for propagation - would need to test) and return false if not, so that the HandActivate event will propagate correctly to the `HandPreparable` component regardless of component order.

In light of this I'm unapproving #8380 and marking as changes required.

2022-02-17 18:37 UTC, MaxIsJoe commented
Done, review pls

2022-02-18 18:16 UTC, Bod9001 commented on UnityProject/Assets/Scripts/Items/HandPreparable.cs
> +			return isPrepared ? false : true;
is this networked?

2022-02-18 18:17 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/Items/HandPreparable.cs
> +			return isPrepared ? false : true;
no it's not, I probably should.

2022-02-18 18:31 UTC, MaxIsJoe commented on UnityProject/Assets/Scripts/Items/HandPreparable.cs
> +			return isPrepared ? false : true;
Done

2022-02-19 14:37 UTC, Bod9001 approved these changes

2022-02-20 00:03 UTC, NoooneyDude approved these changes

2022-02-20 00:03 UTC, merged