Shiver me timbers fixed gun recoil showing for everyone
unitystation/unitystation pull request #8712
Opened 2022-05-23 17:38 UTC by Bod9001

### Purpose
ayy we finally killed the kraken that's been shaking the ship, Crewe be now not sick as a dog!

### Changelog:

CL: [Fix] killed the kraken , fixed gun recoil showing for everyone

2022-05-23 18:05 UTC, Alainx277 requested changes

2022-05-23 18:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Items/Weapons/Gun.cs
> +				RPCShowMuzzleFlash(shooter.GetComponent<NetworkIdentity>());
```suggestion
				RPCShowMuzzleFlash(Identity);
```

2022-05-23 18:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Items/Weapons/Gun.cs
> +			var Identity = shooter.GetComponent<NetworkIdentity>();
`Identity` should probably be lowercase.

2022-05-23 18:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Items/Weapons/Gun.cs
> +				RPCShowMuzzleFlash(shooter.GetComponent<NetworkIdentity>());
Muzzle flash should be shown even if `connectionToClient` is `null`, as it is shown to everyone.

2022-05-25 19:19 UTC, Alainx277 approved these changes

2022-05-25 22:47 UTC, NoooneyDude approved these changes

2022-05-25 22:47 UTC, NoooneyDude commented on UnityProject/Assets/Scripts/Items/Weapons/Gun.cs
> +				RPCShowRecoil(identity.connectionToClient , finalDirection);
The target RPC doesn't work for the host? That's a little surprising.

2022-05-26 07:35 UTC, merged