movement documentation
unitystation/unitystation pull request #8830
Opened 2022-06-14 16:09 UTC by Bod9001

can someone have a look over to see if there's anything I missed

2022-06-15 13:30 UTC, MaxIsJoe commented
I feel like the entire `MovementSynchronisation` needs to be rewritten.
it's not written well and does not explain much except that "hey, this exists"

2022-06-15 17:21 UTC, Bod9001 commented
idk, what to explain about it

2022-06-16 19:05 UTC, Alainx277 requested changes
Maybe some methods could also get comments?

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	[PlayModeOnly] public Vector3 LocalTargetPosition; //The position that tile Push animations Are targeting
Please use the doc comment format so IDEs can show it:
```suggestion
    /// <summary>
    /// The position that tile push animations are targeting
    /// </summary>
	[PlayModeOnly] public Vector3 LocalTargetPosition; 
```

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	[PrefabModeOnly] public bool ChangesDirectionPush = false;  //Tries to change rotatable direction
I don't understand this comment, how does a bool change a "rotatable direction"?

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	public Vector3WithData SetLocalTarget  //Set networking and stuff
I don't think this comment is helpful.

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	private bool isVisible = true; //Is that hidden POS
What does POS stand for? I think we should avoid contractions where possible.

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	public bool isNotPushable; //Can be pushed around
I feel like this is self-evident.

2022-06-16 19:05 UTC, Alainx277 commented on UnityProject/Assets/Scripts/Core/UniversalObjectPhysics.cs
> +	[PlayModeOnly] public int ForcedPushedFrame = 0; //to stop loops
I think it would help if you specified what kind of loops it stops, and how.

2022-06-16 19:05 UTC, Alainx277 commented on docs/development/Whats-Going-On-With-Movement.md
> +<h2>MovementSynchronisation</h2>
This section is incomprehensible to me, I think it may be better to just leave a TODO in there.

2022-11-25 00:18 UTC, closed without merging