MOTD window works again + improvements
unitystation/unitystation pull request #9167
Opened 2022-08-26 07:35 UTC by MaxIsJoe

Fixes #9122 + I've worked on stuff that has been annoying me for some time like how there were 2 different versions of the server info UI which made things pretty hard to keep track of and fix bugs for.

## Changelog:

CL: [Fix] - MOTD window works again

2022-08-26 08:36 UTC, ThatDan123 submitted a review, later dismissed

2022-08-26 08:36 UTC, ThatDan123 commented
Oh tests failing

2022-08-26 08:59 UTC, NoooneyDude commented
😌 was worried for a second there we were modifying the same prefab 🙂

2022-08-26 10:05 UTC, MaxIsJoe commented
should be fixed now

2022-08-26 17:08 UTC, corp-0 commented
> Added "serverDesc.txt" and "serverRules.txt" to streaming assets because they should have been there from the start

remind me to update docker mounting points accordingly to reflect this change after this is merged.

2022-08-26 17:10 UTC, corp-0 commented on UnityProject/Assets/Scripts/UI/Systems/ServerInfoUILobby.cs
> +        public string ServerDiscordID => serverDiscordID;
```suggestion
        public string ServerDiscordID { get; private set;}
```

That way you don't need the private field.

2022-08-26 17:18 UTC, corp-0 commented on UnityProject/Assets/Scripts/UI/Systems/ServerInfoUILobby.cs
> +					UIManager.Instance.ServerInfoUILobby.ServerDesc.text, UIManager.Instance.ServerInfoUILobby.ServerDiscordID, UIManager.Instance.ServerInfoUILobby.ServerRules.text);
separate each argument into its own line.

I thought this was an insanely long chain of stuff at first glance.

2022-08-26 17:20 UTC, corp-0 requested changes
Other than my comments (and assuming this works), I see no other issue worth mentioning.

2022-08-27 06:42 UTC, MaxIsJoe commented
Forgot to push this yesterday, should be done now.

2022-08-28 02:12 UTC, corp-0 approved these changes

2022-08-28 02:12 UTC, merged