application open URL Made safe
unitystation/unitystation pull request #9999
Opened 2023-07-28 22:48 UTC by Bod9001

note second PR because I couldn't update the branch of the old one for some bizarre reason

2023-07-28 22:50 UTC, Bod9001 commented
@corp-0  so  it already validates the URL with 	if (TrySanitizeURL(URL, out var goodURL ))
			{
				Logger.Log($"Opening URL {goodURL}");
				Application.OpenURL(goodURL);
			}
				if (Uri.TryCreate(inputURL, UriKind.Absolute, out Uri uriResult) &&
		    uriResult.Scheme == Uri.UriSchemeHttps)
		{

2023-07-29 00:02 UTC, corp-0 requested changes

2023-07-29 00:02 UTC, corp-0 commented on UnityProject/Assets/Assets.asmdef
> +        "ConfigurationSaves"
why?

2023-07-29 09:57 UTC, Bod9001 commented on UnityProject/Assets/Assets.asmdef
> +        "ConfigurationSaves"
it should be renamed to  safe stuff

2023-07-29 15:15 UTC, merged